### ISSUE TITLE
psl command line tool: add option for reduced output

### ISSUE THREAD

**Issue by hannob** [rockdaboot/libpsl#103]
For scripting purposes I'd find it useful to have a "raw" output that only gives the result.

E.g. if I do:
psl --print-reg-domain foobar.example.com
I get
foobar.example.com: example.com

But I'm really mostly interested in example.com.

Maybe add a "-q" (quiet) parameter that skips the [input]: part at the beginning?

**Comment by rockdaboot** [comment]
Thanks for the suggestion, amended to -b / --batch and pushed with commit 4c68696eb19b33014feed06cce05ae69116da576.
