### ISSUE TITLE
Support non-source-tree builds via autogen.sh

### ISSUE THREAD

**Issue by lanoxx** [rockdaboot/libpsl#104]
Hello,

currently `autogen.sh` does not support non-source-tree builds. The [Gnome Common Migration](https://wiki.gnome.org/Projects/GnomeCommon/Migration) page shows a nice `autogen.sh` template that can be used as a starting point to support non-source-tree builds. It would be nice if you could add support for this.

**Comment by rockdaboot** [comment]
For me, *the* typical out-of-source build is a build from tarball (./configure, make, make check, make install). It succeeds. So I wonder what *exactly* is your problem, especially when you say 'autogen.sh' is somehow involved. Could you give a complete set of commands you use ?

**Comment by lanoxx** [comment]
I am trying to build using the GNOME build tool called jhbuild. It can automatically checkout from git and perform a complete build. However with jhbuild I can only specify that the project uses autotools. It will then invoke autogen.sh for me and expects that autogen.sh calls configure.

**Comment by rockdaboot** [comment]
The 'normal' pattern is to call 'autogen.sh', 'bootstrap' or 'buildconf' and thereafter ./configure.

This is the same for all projects that I regularly work on (or build as dependency):
libunistring, libidn, libidn2, nettle, gnutls, libmicrohttpd, libmetalink, curl, wget, wget2, ...

So there must be something wrong with or missing in jhbuild or (maybe more likely) in your configuration. Or jhbuild is simply the wrong tool for what you are trying to do !?

**Comment by rockdaboot** [comment]
I took a look at the jhbuild docs - they should add another step for a separate ./configure run. That would make the build of standard projects much easier.

If you have more info that might change anything, feel free to reopen.
