### ISSUE TITLE
Autogen.sh should invoke configure at the end of the script

### ISSUE THREAD

**Issue by lanoxx** [rockdaboot/libpsl#105]
Automated build tools such as GNOME`s jhbuild expect that autogen.sh invokes configure when its done preparing the build system. Please consider to call configure rather then printing the configure command.

If you need to disable this conditionally, then consider to make this conditional on an environment variable such as `NOCONFIGURE`, for an example see the [GNOME Common Migration](https://wiki.gnome.org/Projects/GnomeCommon/Migration) page.

**Comment by rockdaboot** [comment]
See my answers on #104 

I could check a `CONFIGURE` env var. But checking `NOCONFIGURE` would change the default behavior of `autogen.sh` which I won't do for several reasons.
