### ISSUE TITLE
make check failed

### ISSUE THREAD

**Issue by JulianIntronati** [rockdaboot/libpsl#108]
After your last commit "make check" does not work on 
trentin-süd-tirol.it
And other similar domains published in lastest psl.
It seems that punycode or utf-8 is not well supported in the function psl_is_public_suffix2.

[test-suite.log](https://github.com/rockdaboot/libpsl/files/2464973/test-suite.log)

**Comment by rockdaboot** [comment]
It's a known issue when building libpsl without any IDN library (libidn, libidn2 or libicu).

It came with one of the latest updates to the Public Suffix List, where someone (likely a MacOS/OSX user) introduced decomposed non-ASCII chars. E.g., for 'ü' they use the UTF-8 sequence '75 cc 88' while the expected NFKC sequence would be 'c3 bc'.

Converting those sequences into NFKC needs a IDN library...

The issue has been reported, but I am not sure if and what they do something about it:
https://github.com/publicsuffix/list/issues/715

**Comment by rockdaboot** [comment]
Here is an MR that fixes the isue upstream: https://github.com/publicsuffix/list/pull/720

**Comment by rockdaboot** [comment]
Finally fixed now, as reference see
  https://github.com/publicsuffix/list/pull/720
  https://github.com/publicsuffix/list/pull/725

Thanks for the heads up.
