### ISSUE TITLE
[discussion] provide tarballs compressed with xz and not gzip (or add it)

### ISSUE THREAD

**Issue by vtorri** [rockdaboot/libpsl#127]
hello

everything in the topic. it will reduce the time downloading the source code

thank you

**Comment by rockdaboot** [comment]
I prefer lzip... WDYT ?

https://www.nongnu.org/lzip/xz_inadequate.html
https://www.nongnu.org/lzip/lzip_benchmark.html

**Comment by vtorri** [comment]
well, i'm not sure that the web page is fair (or maybe too old). For example, in

https://www.nongnu.org/lzip/lzip_benchmark.html#busybox

i tried 

$ echo 'The quick brown fox jumps over the lazy dog.' | xz > fox.xz

then modified a character with emacs in fox.xz, then

$ xz -t fox.xz

and there is no problem with xz 5.2.4 (latest version as of today). It is on Windows. You can try it yourself and see if there are problems or not.

xz is indeed quite used with a lot of projects (i package almost 60 projects (including libpsl) for windows and 18 are using xz, most of the others are using gzip, a few bzip2). If there was really problems with xz, they would not use it

about compression xz vs lzip, what is important imho is that both of them compress a lot better than gzip or bzip2

finally, when i tried to decompress and lzip-compress archive on Windows, I had to install a plugin for 7-zip, which is not very convenient. But i have to do it once, so....

Now, you are author of this project. Do what you want !

**Comment by vtorri** [comment]
well, i'm not sure that the web page is fair (or maybe too old). For example, in

https://www.nongnu.org/lzip/lzip_benchmark.html#busybox

i tried 

$ echo 'The quick brown fox jumps over the lazy dog.' | xz > fox.xz

then modified a character with emacs in fox.xz, then

$ xz -t fox.xz

and there is no problem with xz 5.2.4 (latest version as of today). It is on Windows. You can try it yourself and see if there are problems or not.

xz is indeed quite used with a lot of projects (i package almost 60 projects (including libpsl) for windows and 18 are using xz, most of the others are using gzip, a few bzip2). If there was really problems with xz, they would not use it

about compression xz vs lzip, what is important imho is that both of them compress a lot better than gzip or bzip2

finally, when i tried to decompress and lzip-compress archive on Windows, I had to install a plugin for 7-zip, which is not very convenient. But i have to do it once, so....

Now, you are author of this project. Do what you want !

**Comment by vtorri** [comment]
i've also tried a compression with lzip -m64 -s64MiB and xz -9 on a tar file which is around 300MB. The difference in size is 56KB in favor of lzip. So ok, lzip compresses more, but for a 300MB file, the difference is not so big.

**Comment by daurnimator** [comment]
FWIW, many projects and package managers are moving away from xz and towards [zstd](https://github.com/facebook/zstd).

[this](https://www.nongnu.org/lzip/xz_inadequate.html) is a rather infamous critique of xz as a format.

**Comment by vtorri** [comment]
this link is maybe outdated. As i told you, i have done one of his tests and my result is different from the one in this web page

**Comment by vtorri** [comment]
anyway, do what you want, but use something that compress more than zlib and is available on most distro (is zstd on debian stable ?)

**Comment by vtorri** [comment]
i have around 60 libraries that I package and none are compressed with zstd

**Comment by rockdaboot** [comment]
Additionally using lzip now: https://github.com/rockdaboot/libpsl/releases/tag/libpsl-0.21.0

**Comment by vtorri** [comment]
heh quite small, now

**Comment by Arthur111** [comment]
libpsl-0.21.1.tar.gz -> 8.77 MB
libpsl-0.21.1.tar.lz -> 1.91 MB

libpsl-0.21.1.tar.xz -> 1.51 MB

--> 20.94 % gain
