### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by tp-m** [rockdaboot/libpsl#128]
Hi,

would be nice to have a new tag/release, with all the new stuff and Meson build system support :)

Thanks!

**Comment by rockdaboot** [comment]
Here you are. Have fun !

https://github.com/rockdaboot/libpsl/releases/tag/libpsl-0.21.0

**Comment by tp-m** [comment]
Oh wow, that was quick. Thanks a lot!

**Comment by rockdaboot** [comment]
Ddin't want you to hold off working ;-)
