### ISSUE TITLE
0.21.0 wrongly claims to have meson support.

### ISSUE THREAD

**Issue by maxice8** [rockdaboot/libpsl#129]
Not present in the uploaded tarballs.

![image](https://user-images.githubusercontent.com/30738253/56241238-c71f5f80-606b-11e9-93f3-1f101102477b.png)

**Comment by maxice8** [comment]
![image](https://user-images.githubusercontent.com/30738253/56241399-22e9e880-606c-11e9-826b-bb3f3c4eed37.png)

**Comment by rockdaboot** [comment]
Thanks for pointing out.

Tarballs are made to ease the ./configure && make steps. I personally don't use meson, but would think that a meson user downloads the zipped sources or directly use git clone.

But your are absolutely right, there is no point in not having meson and nmake files in the tarballs.

**Comment by rockdaboot** [comment]
Fix has been pushed, but reveals another issue #130 when building from tarball.

Thanks for reporting.
