### ISSUE TITLE
0.21.0: build fails

### ISSUE THREAD

**Issue by kloczek** [rockdaboot/libpsl#132]
<pre>[tkloczko@domek libpsl-0.21.0]$ make
make  all-recursive
make[1]: Entering directory &apos;/home/tkloczko/rpmbuild/BUILD/libpsl-0.21.0&apos;
Making all in po
make[2]: Entering directory &apos;/home/tkloczko/rpmbuild/BUILD/libpsl-0.21.0/po&apos;
make libpsl.pot-update
make[3]: Entering directory &apos;/home/tkloczko/rpmbuild/BUILD/libpsl-0.21.0/po&apos;
if LC_ALL=C grep &apos;GNU libpsl&apos; ../* 2&gt;/dev/null | grep -v &apos;libtool:&apos; &gt;/dev/null; then \
  package_gnu=&apos;GNU &apos;; \
else \
  package_gnu=&apos;&apos;; \
fi; \
if test -n &apos;tim.ruehsen@gmx.de&apos; || test &apos;tim.ruehsen@gmx.de&apos; = &apos;@&apos;PACKAGE_BUGREPORT&apos;@&apos;; then \
  msgid_bugs_address=&apos;tim.ruehsen@gmx.de&apos;; \
else \
  msgid_bugs_address=&apos;tim.ruehsen@gmx.de&apos;; \
fi; \
case `/usr/bin/xgettext --version | sed 1q | sed -e &apos;s,^[^0-9]*,,&apos;` in \
  &apos;&apos; | 0.[0-9] | 0.[0-9].* | 0.1[0-5] | 0.1[0-5].* | 0.16 | 0.16.[0-1]*) \
    /usr/bin/xgettext --default-domain=libpsl --directory=.. \
      --add-comments=TRANSLATORS: --keyword=_ --keyword=N_  \
      --files-from=./POTFILES.in \
      --copyright-holder=&apos;Tim Ruehsen&apos; \
      --msgid-bugs-address=&quot;$msgid_bugs_address&quot; \
    ;; \
  *) \
    /usr/bin/xgettext --default-domain=libpsl --directory=.. \
      --add-comments=TRANSLATORS: --keyword=_ --keyword=N_  \
      --files-from=./POTFILES.in \
      --copyright-holder=&apos;Tim Ruehsen&apos; \
      --package-name=&quot;${package_gnu}libpsl&quot; \
      --package-version=&apos;0.21.0&apos; \
      --msgid-bugs-address=&quot;$msgid_bugs_address&quot; \
    ;; \
esac
test ! -f libpsl.po || { \
  if test -f ./libpsl.pot; then \
    sed -f remove-potcdate.sed &lt; ./libpsl.pot &gt; libpsl.1po &amp;&amp; \
    sed -f remove-potcdate.sed &lt; libpsl.po &gt; libpsl.2po &amp;&amp; \
    if cmp libpsl.1po libpsl.2po &gt;/dev/null 2&gt;&amp;1; then \
      rm -f libpsl.1po libpsl.2po libpsl.po; \
    else \
      rm -f libpsl.1po libpsl.2po ./libpsl.pot &amp;&amp; \
      mv libpsl.po ./libpsl.pot; \
    fi; \
  else \
    mv libpsl.po ./libpsl.pot; \
  fi; \
}
make[3]: Leaving directory &apos;/home/tkloczko/rpmbuild/BUILD/libpsl-0.21.0/po&apos;
test ! -f ./libpsl.pot || \
  test -z &quot;&quot; || make 
make[2]: Leaving directory &apos;/home/tkloczko/rpmbuild/BUILD/libpsl-0.21.0/po&apos;
Making all in include
make[2]: Entering directory &apos;/home/tkloczko/rpmbuild/BUILD/libpsl-0.21.0/include&apos;
make[2]: Nothing to be done for &apos;all&apos;.
make[2]: Leaving directory &apos;/home/tkloczko/rpmbuild/BUILD/libpsl-0.21.0/include&apos;
Making all in src
make[2]: Entering directory &apos;/home/tkloczko/rpmbuild/BUILD/libpsl-0.21.0/src&apos;
make  all-am
make[3]: Entering directory &apos;/home/tkloczko/rpmbuild/BUILD/libpsl-0.21.0/src&apos;
make[3]: Nothing to be done for &apos;all-am&apos;.
make[3]: Leaving directory &apos;/home/tkloczko/rpmbuild/BUILD/libpsl-0.21.0/src&apos;
make[2]: Leaving directory &apos;/home/tkloczko/rpmbuild/BUILD/libpsl-0.21.0/src&apos;
Making all in tools
make[2]: Entering directory &apos;/home/tkloczko/rpmbuild/BUILD/libpsl-0.21.0/tools&apos;
make[2]: Nothing to be done for &apos;all&apos;.
make[2]: Leaving directory &apos;/home/tkloczko/rpmbuild/BUILD/libpsl-0.21.0/tools&apos;
Making all in docs/libpsl
make[2]: Entering directory &apos;/home/tkloczko/rpmbuild/BUILD/libpsl-0.21.0/docs/libpsl&apos;
Makefile:1001: warning: overriding recipe for target &apos;clean-local&apos;
Makefile:919: warning: ignoring old recipe for target &apos;clean-local&apos;
make[2]: Leaving directory &apos;/home/tkloczko/rpmbuild/BUILD/libpsl-0.21.0/docs/libpsl&apos;
Making all in fuzz
make[2]: Entering directory &apos;/home/tkloczko/rpmbuild/BUILD/libpsl-0.21.0/fuzz&apos;
make[2]: Nothing to be done for &apos;all&apos;.
make[2]: Leaving directory &apos;/home/tkloczko/rpmbuild/BUILD/libpsl-0.21.0/fuzz&apos;
Making all in tests
make[2]: Entering directory &apos;/home/tkloczko/rpmbuild/BUILD/libpsl-0.21.0/tests&apos;
make[2]: *** No rule to make target &apos;../list/public_suffix_list.dat&apos;, needed by &apos;psl.dafsa&apos;.  Stop.
make[2]: Leaving directory &apos;/home/tkloczko/rpmbuild/BUILD/libpsl-0.21.0/tests&apos;
make[1]: *** [Makefile:535: all-recursive] Error 1
make[1]: Leaving directory &apos;/home/tkloczko/rpmbuild/BUILD/libpsl-0.21.0&apos;
</pre>

**Comment by kloczek** [comment]
Above was with https://github.com/rockdaboot/libpsl/releases/download/libpsl-0.21.0/libpsl-0.21.0.tar.gz

On release page is listed second generated on demand tar https://github.com/rockdaboot/libpsl/archive/libpsl-0.21.0.tar.gz
Issue with that tar is exactly the same.
Additionally because you are using in release tags libpsl-<version> inside it has base directory like libpsl-libpsl-<version>/

**Comment by rockdaboot** [comment]
These 'source' archives are auto-generated by Github but they miss git data and git submodule data. 

You could
```
git clone https://github.com/publicsuffix/list
```

and ignore errors seen from `./autogen.sh`.

The git tags are fine this way. Many projects use it like that and it's actually *good* to have project name and tag name in the directory, even if the string 'libpsl' is a bit redundant (but that's another Github issue).

**Comment by kloczek** [comment]
I can do many things byt I did not open this ticket to ask you about what I can do :/
Just have look around and try to find how many projects are using that way of tagging.
Really that small change makes easier to package every package which does not use your methodology.
Example https://gitlab.gnome.org/GNOME/ repos.

**Comment by rockdaboot** [comment]
> I can do many things byt I did not open this ticket to ask you about what I can do :/

There might be other people in search of knowledge. Please don't consider a public Github issue being the same as a PM.

I am definitely in a sort of a bubble regarding the projects I maintain or work on. These are
```
wget2-1.99.1
libidn2-2.1.1
libidn-1-12
cares-1_7_0
curl-7_15_0
gnutls_3_6_7
libhsts-0.1.0
libpsl-0.21.0
nettle_3.4.1_release_20181204
```
against
```
v1.20.3 (wget)
v0.9.63 (libmicrohttpd)
```

But as I said, the tagging isn't a problem at all. It's the missing git submodule initialization. Not sure how to disable/remove these "source" archives from the release page.

**Comment by kloczek** [comment]
> wget2-1.99.1
> libidn2-2.1.1
> libidn-1-12
> cares-1_7_0
> curl-7_15_0
> gnutls_3_6_7
> libhsts-0.1.0
> libpsl-0.21.0
> nettle_3.4.1_release_20181204

You just formed the list with few one of the baddies maintained projects from my list.
nettle and curl are really high on my list.
Now try to think that some people are using gitlab/github API to detect that some new release has been made to automatically download and perform test build.
Such freakish and not standardised versioning makes such things harder.
Do you see it now?

**Comment by kloczek** [comment]
Actually looks like it was issue with Fedora spec file.
Closing.

PS. Please be compliant with most of the git projects about tagging convention :)

**Comment by rockdaboot** [comment]
I will follow https://semver.org/ for my projects in the future. Thanks for raising the issue.
