### ISSUE TITLE
0.21.0: gtk-doc warnings and errors

### ISSUE THREAD

**Issue by kloczek** [rockdaboot/libpsl#133]
<pre>gtkdoc-fixxref --module=libpsl --module-dir=html --html-dir=/usr/share/gtk-doc/html 
html/libpsl-Public-Suffix-List-functions.html:311: warning: no link for: &quot;api-index-0.1&quot; -&gt; (0.1).
html/libpsl-Public-Suffix-List-functions.html:317: warning: no link for: &quot;FILE:CAPS&quot; -&gt; (&lt;span class=&quot;type&quot;&gt;FILE&lt;/span&gt;).
html/libpsl-Public-Suffix-List-functions.html:376: warning: no link for: &quot;api-index-0.16&quot; -&gt; (0.16).
html/libpsl-Public-Suffix-List-functions.html:710: warning: no link for: &quot;api-index-0.10.0&quot; -&gt; (0.10.0).
html/libpsl-Public-Suffix-List-functions.html:849: warning: no link for: &quot;api-index-0.2.5&quot; -&gt; (0.2.5).
html/libpsl-Public-Suffix-List-functions.html:879: warning: no link for: &quot;api-index-0.11.0&quot; -&gt; (0.11.0).
html/libpsl-Public-Suffix-List-functions.html:941: warning: no link for: &quot;api-index-0.4&quot; -&gt; (0.4).
html/libpsl-Public-Suffix-List-functions.html:965: warning: no link for: &quot;api-index-0.19&quot; -&gt; (0.19).
touch html-build.stamp
make[2]: Leaving directory &apos;/home/tkloczko/rpmbuild/BUILD/libpsl-libpsl-0.21.0/docs/libpsl&apos;
make[2]: Entering directory &apos;/home/tkloczko/rpmbuild/BUILD/libpsl-libpsl-0.21.0/docs/libpsl&apos;
Note: meta source : no *info/productname or alternative            libpsl
Note: meta source : see http://www.docbook.org/tdg5/en/html/produ  libpsl
Note: meta source : no refentry/refmeta/refmiscinfo@class=source   libpsl
Note: meta source : see http://www.docbook.org/tdg5/en/html/refmi  libpsl
Note: meta version: no *info/productnumber or alternative          libpsl
Note: meta version: see http://www.docbook.org/tdg5/en/html/produ  libpsl
Note: meta version: no refentry/refmeta/refmiscinfo@class=version  libpsl
Note: meta version: see http://www.docbook.org/tdg5/en/html/refmi  libpsl
Warn: meta source : using &quot;LIBPSL Library&quot; for &quot;source&quot;            libpsl
Note: meta manual : no titled ancestor of refentry                 libpsl
Note: meta manual : no refentry/refmeta/refmiscinfo@class=manual   libpsl
Note: meta manual : see http://www.docbook.org/tdg5/en/html/refmi  libpsl
Warn: meta manual : using &quot;LIBPSL Library&quot; for &quot;manual&quot;            libpsl
Warn: meta author : no refentry/info/author                        libpsl
Note: meta author : see http://www.docbook.org/tdg5/en/html/autho  libpsl
Warn: meta author : no author data, so inserted a fixme            libpsl
Error: no ID for constraint linkend: &quot;void&quot;.
Error: no ID for constraint linkend: &quot;int&quot;.
Error: no ID for constraint linkend: &quot;int&quot;.
Error: no ID for constraint linkend: &quot;char&quot;.
Error: no ID for constraint linkend: &quot;char&quot;.
Error: no ID for constraint linkend: &quot;int&quot;.
Error: no ID for constraint linkend: &quot;int&quot;.
Error: no ID for constraint linkend: &quot;int&quot;.
Error: no ID for constraint linkend: &quot;time-t&quot;.
Error: no ID for constraint linkend: &quot;char&quot;.
Error: no ID for constraint linkend: &quot;char&quot;.
Error: no ID for constraint linkend: &quot;int&quot;.
Error: no ID for constraint linkend: &quot;int&quot;.
Error: no ID for constraint linkend: &quot;char&quot;.
Error: no ID for constraint linkend: &quot;char&quot;.
Error: no ID for constraint linkend: &quot;int&quot;.
Error: no ID for constraint linkend: &quot;void&quot;.
Error: no ID for constraint linkend: &quot;char&quot;.
Error: no ID for constraint linkend: &quot;NULL:CAPS&quot;.
Error: no ID for constraint linkend: &quot;api-index-0.1&quot;.
Error: no ID for constraint linkend: &quot;FILE:CAPS&quot;.
Error: no ID for constraint linkend: &quot;NULL:CAPS&quot;.
Error: no ID for constraint linkend: &quot;api-index-0.1&quot;.
Error: no ID for constraint linkend: &quot;char&quot;.
Error: no ID for constraint linkend: &quot;NULL:CAPS&quot;.
Error: no ID for constraint linkend: &quot;NULL:CAPS&quot;.
Error: no ID for constraint linkend: &quot;NULL:CAPS&quot;.
Error: no ID for constraint linkend: &quot;NULL:CAPS&quot;.
Error: no ID for constraint linkend: &quot;api-index-0.16&quot;.
Error: no ID for constraint linkend: &quot;NULL:CAPS&quot;.
Error: no ID for constraint linkend: &quot;api-index-0.1&quot;.
Error: no ID for constraint linkend: &quot;void&quot;.
Error: no ID for constraint linkend: &quot;api-index-0.1&quot;.
Error: no ID for constraint linkend: &quot;int&quot;.
Error: no ID for constraint linkend: &quot;char&quot;.
Error: no ID for constraint linkend: &quot;api-index-0.1&quot;.
Error: no ID for constraint linkend: &quot;int&quot;.
Error: no ID for constraint linkend: &quot;char&quot;.
Error: no ID for constraint linkend: &quot;int&quot;.
Error: no ID for constraint linkend: &quot;api-index-0.1&quot;.
Error: no ID for constraint linkend: &quot;char&quot;.
Error: no ID for constraint linkend: &quot;char&quot;.
Error: no ID for constraint linkend: &quot;NULL:CAPS&quot;.
Error: no ID for constraint linkend: &quot;NULL:CAPS&quot;.
Error: no ID for constraint linkend: &quot;api-index-0.1&quot;.
Error: no ID for constraint linkend: &quot;char&quot;.
Error: no ID for constraint linkend: &quot;char&quot;.
Error: no ID for constraint linkend: &quot;NULL:CAPS&quot;.
Error: no ID for constraint linkend: &quot;NULL:CAPS&quot;.
Error: no ID for constraint linkend: &quot;api-index-0.1&quot;.
Error: no ID for constraint linkend: &quot;int&quot;.
Error: no ID for constraint linkend: &quot;api-index-0.1&quot;.
Error: no ID for constraint linkend: &quot;int&quot;.
Error: no ID for constraint linkend: &quot;api-index-0.1&quot;.
Error: no ID for constraint linkend: &quot;int&quot;.
Error: no ID for constraint linkend: &quot;api-index-0.10.0&quot;.
Error: no ID for constraint linkend: &quot;time-t&quot;.
Error: no ID for constraint linkend: &quot;api-index-0.1&quot;.
Error: no ID for constraint linkend: &quot;char&quot;.
Error: no ID for constraint linkend: &quot;api-index-0.1&quot;.
Error: no ID for constraint linkend: &quot;char&quot;.
Error: no ID for constraint linkend: &quot;api-index-0.1&quot;.
Error: no ID for constraint linkend: &quot;int&quot;.
Error: no ID for constraint linkend: &quot;api-index-0.10.0&quot;.
Error: no ID for constraint linkend: &quot;int&quot;.
Error: no ID for constraint linkend: &quot;char&quot;.
Error: no ID for constraint linkend: &quot;char&quot;.
Error: no ID for constraint linkend: &quot;api-index-0.1&quot;.
Error: no ID for constraint linkend: &quot;char&quot;.
Error: no ID for constraint linkend: &quot;api-index-0.16&quot;.
Error: no ID for constraint linkend: &quot;char&quot;.
Error: no ID for constraint linkend: &quot;api-index-0.2.5&quot;.
Error: no ID for constraint linkend: &quot;int&quot;.
Error: no ID for constraint linkend: &quot;int&quot;.
Error: no ID for constraint linkend: &quot;api-index-0.11.0&quot;.
Error: no ID for constraint linkend: &quot;char&quot;.
Error: no ID for constraint linkend: &quot;char&quot;.
Error: no ID for constraint linkend: &quot;char&quot;.
Error: no ID for constraint linkend: &quot;char&quot;.
Error: no ID for constraint linkend: &quot;NULL:CAPS&quot;.
Error: no ID for constraint linkend: &quot;NULL:CAPS&quot;.
Error: no ID for constraint linkend: &quot;NULL:CAPS&quot;.
Error: no ID for constraint linkend: &quot;api-index-0.4&quot;.
Error: no ID for constraint linkend: &quot;void&quot;.
Error: no ID for constraint linkend: &quot;char&quot;.
Error: no ID for constraint linkend: &quot;free&quot;.
Error: no ID for constraint linkend: &quot;api-index-0.19&quot;.
Note: Writing libpsl.3
</pre>

**Comment by rockdaboot** [comment]
Pushed a few things, but even before couldn't I reproduce your error list. Currently see
```
  DOC   Building HTML

          In gtk-doc.xsl: For acronym (Stable) no value found!
        
  DOC   Fixing cross-references
html/libpsl-Public-Suffix-List-functions.html:313: warning: no link for: "NULL:CAPS" -> (<code class="literal">NULL</code>).
html/libpsl-Public-Suffix-List-functions.html:321: warning: no link for: "FILE:CAPS" -> (<span class="type">FILE</span>).
```

No idea how to silence / fix those.
