### ISSUE TITLE
0.21.0: test suite fails

### ISSUE THREAD

**Issue by kloczek** [rockdaboot/libpsl#134]
<pre>+ /usr/bin/ninja test -v -j4 -C x86_64-redhat-linux-gnu
ninja: Entering directory `x86_64-redhat-linux-gnu&apos;
[0/1] /usr/bin/meson test --no-rebuild --print-errorlogs
<font color="#CD0000"><b>1/8 test-is-public                          FAIL     0.04 s (exit status 1)</b></font>
2/8 test-is-public-all                      OK       0.23 s 
3/8 test-is-cookie-domain-acceptable        OK       0.05 s 
4/8 test-is-public-builtin                  OK       0.02 s 
5/8 test-registrable-domain                 OK       0.01 s 
6/8 libpsl_idn2_fuzzer                      OK       0.03 s 
7/8 libpsl_idn2_load_fuzzer                 OK       0.30 s 
8/8 libpsl_idn2_load_dafsa_fuzzer           OK       0.02 s 

Ok:                    7
Expected Fail:         0
Fail:                  1
Unexpected Pass:       0
Skipped:               0
Timeout:               0

The output from the failed tests:

1/8 test-is-public                          FAIL     0.04 s (exit status 1)

--- command ---
/home/tkloczko/rpmbuild/BUILD/libpsl-libpsl-0.21.0/x86_64-redhat-linux-gnu/tests/test-is-public
--- stdout ---
loaded 8640 suffixes and 8 exceptions
psl_check_version_number(001403) is 001404
Summary: 1 out of 55 tests failed
-------

Full log written to /home/tkloczko/rpmbuild/BUILD/libpsl-libpsl-0.21.0/x86_64-redhat-linux-gnu/meson-logs/testlog.txt
FAILED: meson-test 
</pre>
[testlog.txt](https://github.com/rockdaboot/libpsl/files/3100042/testlog.txt)

**Comment by rockdaboot** [comment]
The latest master should already contain a fix. You can download a zip archive via 'clone or download' on the libpsl main page. The meson build contained a hard-coded libpsl version that wasn't updated in the release. Would be cool if you can test and report back if latest master fixes this for you.

**Comment by rockdaboot** [comment]
Assuming 'no feedback' as 'now works', closing.

**Comment by kloczek** [comment]
In the same build env build of libpsl 0.21.2 is OK.
