### ISSUE TITLE
psl_str_to_utf8lower max str_length

### ISSUE THREAD

**Issue by dwaas** [rockdaboot/libpsl#135]
The following looks like a small string optimisation. I'm wondering whether it's [legal](https://www.freesoft.org/CIE/RFC/1035/9.htm) to have hostnames bigger than that at all and if so, why?

Thanks in advance for the replies. :)

https://github.com/rockdaboot/libpsl/blob/87715ba378854a98f7e0f54280613f041f36d824/src/psl.c#L1741-L1754

**Comment by rockdaboot** [comment]
Well, that function converts strings, not hostnames :-)

**Comment by dwaas** [comment]
Danke. :)

Btw, any reason behind the specific number `256`?

**Comment by rockdaboot** [comment]
Gerne :-)

> Btw, any reason behind the specific number 256?

My numbers are normally 2^N. 128 seemed to be to low, 512 too high ;-)
