### ISSUE TITLE
Build issues with 0.21.0 release

### ISSUE THREAD

**Issue by rezso** [rockdaboot/libpsl#143]
- the release tarball doesn't contains Makefile.in, so the configure fails
- after running autogen.sh and configure, the build is successful, but the library version is 5.3.2, iunstead of 8.2.3
- meson build create the libpsl.so, without any version number. This breaks the dependency of other packages, because libpsl.so.5 (or any version numbered libpsl.so) is missing.

**Comment by nirbheek** [comment]
> meson build create the libpsl.so, without any version number. This breaks the dependency of other packages, because libpsl.so.5 (or any version numbered libpsl.so) is missing.

This is fixed by https://github.com/rockdaboot/libpsl/commit/841ae6ddddf848a05509e27ad516e4d5c1758f10.

**Comment by rockdaboot** [comment]
> the release tarball doesn't contains Makefile.in, so the configure fails.

Did you download the tar'ed sources ?

The current tarball contains the Makefile.in:
```
$ tar tvfz libpsl-0.21.0.tar.gz |grep Makefile.in
-rw-r--r-- 200/100       32876 2019-04-16 15:11 libpsl-0.21.0/Makefile.in
-rw-r--r-- 200/100       16162 2016-12-14 12:04 libpsl-0.21.0/po/Makefile.in.in
-rw-r--r-- 200/100       18723 2019-04-16 15:11 libpsl-0.21.0/include/Makefile.in
-rw-r--r-- 200/100       28267 2019-04-16 15:11 libpsl-0.21.0/src/Makefile.in
-rw-r--r-- 200/100       24821 2019-04-16 15:11 libpsl-0.21.0/tools/Makefile.in
-rw-r--r-- 200/100       33448 2019-04-16 15:11 libpsl-0.21.0/docs/libpsl/Makefile.in
-rw-r--r-- 200/100       52436 2019-04-16 15:14 libpsl-0.21.0/fuzz/Makefile.in
-rw-r--r-- 200/100       40943 2019-04-16 15:11 libpsl-0.21.0/tests/Makefile.in
-rw-r--r-- 200/100       14786 2019-04-16 15:11 libpsl-0.21.0/msvc/Makefile.in
```

**Comment by rockdaboot** [comment]
> after running autogen.sh and configure, the build is successful, but the library version is 5.3.2, iunstead of 8.2.3

5.3.2 is correct, this is different from the versions in configure.ac (I don't have the algorithms at hand that calculate configure.ac numbers to SONAME).
