### ISSUE TITLE
Feature request: strict mode for --print-reg-domain/--print-unreg-domain with invalid TLDs

### ISSUE THREAD

**Issue by hannob** [rockdaboot/libpsl#147]
Right now when I use the psl tool with a hostname with a nonexisting TLD it seems to consider the part after the last dot as the TLD. E.g.:
```
$ psl --print-reg-domain sub.example.xyxy
sub.example.xyxy: example.xyxy
```

I guess the rationale behind this is that in case of a rightmost label that is not in the suffix list yet it's assumed that this might be a new TLD.

Now what I'd like to have is a feature that in such cases doesn't print out anything, but returns an error. Use cases would be something where you iterate over a list of hostnames and want their registered domain names, but you have some garbage in there (specifically IP adresses) that you don't want to generate any output, but just ignore.

Do you think something like this could be implemented? This could be called the "strict" mode (--strict) and apply to --print-reg-domain and --print-unreg-domain (and maybe other options).

E.g. I'd expect something like:
```
$ psl --print-reg-domain --strict sub.example.xyxy
sub.example.xyxy: 
$ echo $?
1
```
And in batch mode:
```
$ psl --print-reg-domain -b --strict sub.example.xyxy

$ echo $?
1
```

**Comment by rockdaboot** [comment]
Hi,

your question imposes that the Public Suffix List is normative or authoritative regarding the existing TLDs. A similar question has been raised before, please see #84.
