### ISSUE TITLE
maybe mention dependencies?

### ISSUE THREAD

**Issue by MaartenW** [rockdaboot/libpsl#157]
There are a couple of dependencies, for building from git, which are not mentioned in the README:

```
autoconf
autopoint
gtk-doc
```

**Comment by rockdaboot** [comment]
A list of dependencies is indeed missing. It would be super helpful if someone can provide a PR for it.
Btw, the mentioned deps are for building from git only.

**Comment by mascguy** [comment]
Folks, I'm a MacPorts maintainer, and have a question regarding one of the dependencies.

At present, our `libpsl` port has `glib2` as a build and runtime dependency. And indeed, there are references to it in the generated makefile, configure script, etc. However, based on testing, it looks like `libpsl` will also build and run without it. (Haven't run exhaustive tests, but sanity checks and such pass.)

So, I'm curious whether `glib2` is truly a necessary dependency? And if not, are any features/functionality lost when building without it? (The goal here is to whittle down the dependency list for `libpsl`, as it's a foundational component for plenty of other software.)

Thanks,
-Chris Nielsen

**Comment by rockdaboot** [comment]
@mascguy `glib2` is not a dependency. You could ask the port maintainer, it's either a bug or a work-around for something else (that I am not aware of).

**Comment by fungilife** [comment]
I came here (repo) to investigate the reason why Arch-Linux moved python from a makedependency to a running dependency?  Therefore, making it an absolute necessity to be installed if libpsl is installed.   

I am digging and can't seem to find the reason.  I understand the makedependency which had always been there, but not the coexistence necessity when the lib is installed.

**Comment by eli-schwartz** [comment]
I can think of two possibilities.

The most likely possibility based on https://sysdfree.wordpress.com/2020/01/03/292/ is that it is a conspiracy between Arch Linux and Facebook to deprive users of their rights when using Free Software.

...

The other possibility is that the package installs an optional python script.

**Comment by fungilife** [comment]
Apart of your personal issues with sysdfree, what script is this that did not exist in previous versions?

https://en.wikipedia.org/wiki/Deterministic_acyclic_finite_state_automaton

You could have simply stated that this is important enough to have 75MB of packages more when they weren't necessary, a google.chrome copy paste script .. OK

Gog it!

**Comment by rockdaboot** [comment]
The python script can be useful whenever you want to create the DAFSA blob. But it is by no means a runtime dependency for libpsl.

**Comment by eli-schwartz** [comment]
As I said, the script is *optional*.

You should speak directly to your vendor (in this case Arch Linux) to determine why they decided it was in the best interests of their users to make an optional component be mandatory.

**Comment by fungilife** [comment]
Thank you for the clarification @rockdaboot 
I am trying to figure out in what circumstances this script is called up to create this blob ... not the easiest thing to do.

**Comment by eli-schwartz** [comment]
The main thing that comes to mind is if you want to distribute a standalone PSL list as a dafsa data file, so you get the PSL list and depend on libpsl's optional script to compile it.

**Comment by fungilife** [comment]
Thank you @eli-schwartz 
I suppose you know the experiment with the caged monkeys, the hanging high bananas, that after years nobody dares to touch but nobody knows why.

curl demands libpsl to be present
makepkg demands that curl is present
so a minimal building environment now demands python and libnsl present

and there will be nobody left alive to know why

A conspiracy would have required at least 2 packagers to do this :)
