### ISSUE TITLE
Tools and tests don't link on Windows, because of missing symbols

### ISSUE THREAD

**Issue by madebr** [rockdaboot/libpsl#160]
This is on Visual Studio.

When building a static library, linking the tools/tests fail because the define `PSL_STATIC` is not passed.
This causes linking to fail with missing `_imp_psl_*` symbols.

**Comment by rockdaboot** [comment]
Please feel free to come up with a patch :-)

**Comment by rockdaboot** [comment]
You have to set PSL_STATIC manually, like in
```
msvc/config-msvc.mak:BASE_CFLAGS = $(BASE_CFLAGS) /DPSL_STATIC
msvc/config-msvc.mak.in:BASE_CFLAGS = $(BASE_CFLAGS) /DPSL_STATIC
```

You surely can do that in Visual Studio as well (last time I used the MS C/C++ IDE was in the 1990s.)
