### ISSUE TITLE
Doc on FSF wiki looks ancient - FYI (not a bug)

### ISSUE THREAD

**Issue by aixtools** [rockdaboot/libpsl#165]
Not a bug for here - but as it is the link that cam up first when I looked for libpsl (for use with curl) - I thought I'd mention that the page https://directory.fsf.org/wiki/Libpsl mentions a very old version of libpsl.

Fortunately it also has a link to this github project - however - maybe the page should refer people here - rather than to an ancient debian distribution.

FYI

Feel free to close at your convenience.

**Comment by rockdaboot** [comment]
I have an account but fail to login. Even after two password resets, that crap site doesn't work. Have to close this before I get into a rage 😆
