### ISSUE TITLE
psl-make-dafsa /usr/bin/env: ‘python’: No such file or directory

### ISSUE THREAD

**Issue by crvigh** [rockdaboot/libpsl#169]
build fails in debian:

```
Making all in src
make[2]: Entering directory '/home/carl/.cache/jhbuild/build/libpsl-0.21.0/src'
/home/carl/jhbuild/checkout/libpsl-0.21.0/src/psl-make-dafsa --output-format=cxx+ "/home/carl/jhbuild/checkout/libpsl-0.21.0/list/public_suffix_list.dat" suffixes_dafsa.h
/usr/bin/env: ‘python’: No such file or directory
make[2]: *** [Makefile:812: suffixes_dafsa.h] Error 127
make[2]: Leaving directory '/home/carl/.cache/jhbuild/build/libpsl-0.21.0/src'
make[1]: *** [Makefile:536: all-recursive] Error 1
make[1]: Leaving directory '/home/carl/.cache/jhbuild/build/libpsl-0.21.0'
make: *** [Makefile:445: all] Error 2
```
Fix: https://salsa.debian.org/debian/libpsl/-/blob/debian/master/debian/patches/0002-make-psl-make-dafsa-py3-based.patch

**Comment by rockdaboot** [comment]
Some distros don't provide `python` any more. On others it's either linked to python2 or python3.
The build works in any known case, given that you provide a `python` command.

So make sure you have python3 installed (python2 is past end-of-life).
Then, e.g. on Debian Linux, `sudo ln -s /usr/bin/python3 /usr/bin/python` and try again.
