### ISSUE TITLE
Readme cites non-existent configure script for building without git

### ISSUE THREAD

**Issue by MartinHowe426** [rockdaboot/libpsl#170]
The README file says one can do a traditional build (i.e., without requiring git) use the usual ./configure -> make -> make check; however there is no configure script in the package. Generating it with autogen.sh requires git, thus defeating the purpose, and using autoconf to attempt to generate it complains about missing m4 macros, despite my having a recent (4.4.18) m4 on my system.

```
configure.ac:5: error: possibly undefined macro: AM_INIT_AUTOMAKE
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure.ac:36: error: possibly undefined macro: AM_GNU_GETTEXT
configure.ac:37: error: possibly undefined macro: AM_GNU_GETTEXT_VERSION
configure.ac:45: error: possibly undefined macro: AM_CONDITIONAL
configure.ac:65: error: possibly undefined macro: AC_MSG_ERROR
configure.ac:73: error: possibly undefined macro: AM_PATH_PYTHON
configure.ac:82: error: possibly undefined macro: AC_LINK_IFELSE
configure.ac:83: error: possibly undefined macro: AC_LANG_PROGRAM
configure.ac:188: error: possibly undefined macro: AC_SEARCH_LIBS
configure.ac:221: error: possibly undefined macro: AC_MSG_CHECKING
configure.ac:226: error: possibly undefined macro: AC_MSG_RESULT
configure.ac:291: error: possibly undefined macro: AM_ICONV
```
Please, if building without git is no longer supported, remove the reference from the README file? Or else include the configure file for building without git.

(To answer the obvious question, the target system doesn't have a working git in the repositories and compiling git from scratch would be a long-winded process that is best avoided.)

**Comment by rockdaboot** [comment]
Oh, thank you for the report. Not sure why the ./configure file is missing. Creating a new tarball for 0.21.1 locally contains it. Have to check what went wrong here :-).

**Comment by rockdaboot** [comment]
Now I am confused. If you go to https://github.com/rockdaboot/libpsl/releases/tag/0.21.1 and download `libpsl-0.21.1.tar.gz`, don't you have a ./configure script ? There is another tar.gz that is just an archive of the git repo (so not ./configure script).

Yeah, that is all a bit confusing... not sure how to disable the automatic generation of those repo archives done by Github.

**Comment by MartinHowe426** [comment]
Well, I don't know what's happened, but thanks very much - the file you just linked to has the script.

**Comment by rockdaboot** [comment]
Haha, happend to me also on the first try. It's just easy to confuse the two tar.gz files.
