### ISSUE TITLE
Mem-leak in test-registrable-domain.exe

### ISSUE THREAD

**Issue by gvanem** [rockdaboot/libpsl#175]
When building for MSVC (x86) in `_DEBUG` mode; options `-MDd -DBUILTIN_GENERATOR_LIBICU=1 -DWITH_LIBICU=1`,
there is this memory-leak report which I suspect is from inside ICU (since no file-names or lines are shown):
```
have 9189 suffixes and 8 exceptions
Summary: All 95 tests passed
Dumping objects ->
{528} normal block at 0x0C138B78, 12252 bytes long.
 Data: <                > 01 00 00 80 00 00 00 00 00 00 00 00 01 00 00 80
{527} normal block at 0x0C149A20, 52 bytes long.
 Data: <x    @ g A g    > 78 8B 13 0C A0 40 82 67 E0 41 82 67 00 00 00 00
{526} normal block at 0x00DB3B60, 228 bytes long.
 Data: <         <    _h> E4 00 00 00 00 00 00 00 E0 3C 13 0C 00 9A 5F 68
{525} normal block at 0x0C133CE0, 28 bytes long.
 Data: <    p _h        > 00 00 00 00 70 99 5F 68 00 00 00 00 01 00 00 00
{524} normal block at 0x0C133FF8, 28 bytes long.
 Data: <    0  g        > 00 00 00 00 30 1D C8 67 00 00 00 00 01 00 00 00
{523} normal block at 0x0C133BC0, 28 bytes long.
 Data: <D  g   g   g    > 44 95 8E 67 00 85 8F 67 90 85 8F 67 01 00 00 00
Object dump complete.
0 bytes in 0 Free Blocks.
0 bytes in 0 Normal Blocks.
36459 bytes in 502 CRT Blocks.
0 bytes in 0 Ignore Blocks.
0 bytes in 0 Client Blocks.
Largest number used: 59979 bytes.
Total allocations: 67519 bytes.
Detected memory leaks!
```

I suspect the `test_iso()` function triggers this `12252 bytes long` leak.

My ICU package was produced by `vcpkg install icu:x86-windows-static`. And yes, I do link with the ICU `*d.lib`  libraries.

No leaks in any other test-program.

**Comment by rockdaboot** [comment]
Not sure what I can do. Some libraries allocate buffers for regular used data on first use and then never free it again 🤷🏻‍♂️ 

If you amend the code to run test_iso() in a loop (e.g. 100 times) and the reported amount of memory doesn't increase, then we should not waste our time on this.

**Comment by gvanem** [comment]
> If you amend the code to run test_iso() in a loop (e.g. 100 times) and the reported amount of memory doesn't increase, 

That's exactly what is happening. 

OK, so I'm closing this.
