### ISSUE TITLE
Make a proper python package for psl-make-dafsa

### ISSUE THREAD

**Issue by KOLANICH** [rockdaboot/libpsl#176]

**Comment by eli-schwartz** [comment]
Maybe I'm missing something here... psl-make-dafsa is a script, not a library, so what do you want packaged exactly?

**Comment by rockdaboot** [comment]
`psl-make-dafsa` is a Python tool. I can see how it would be useful as a stand-alone python package, e.g. installable with `pip install psl-make-dafsa`. It would remove the need to maintain it as part of libpsl. But python packaging is not my expertise 🤷🏻

**Comment by eli-schwartz** [comment]
A standalone python package in this case just means a separate repo with a Makefile that `make install`s the script to `$(DESTDIR)$(PREFIX)/bin`. I don't think it's particularly worth looking into and it's not clear how libpsl would use it other than by acquiring it as a git submodule.

**Comment by rockdaboot** [comment]
The `psl-make-dafsa` tool doesn't seem generic enough for a separate project/repository.
