### ISSUE TITLE
Help for downstream packagers

### ISSUE THREAD

**Issue by dago** [rockdaboot/libpsl#18]
Hi,

it would be nice if there were some changes to make life for downstream packagers easier:
1. Use releases with names. At the moment the releases are just named with the version like 0.6.2, it would be better if they would be named libpsl-0.6.2 for tarsal consistency.
2. The tarballs are not bootstrapped. I understand that generated stuff should not be in the repo, but the tarballs should contain configure as bootstrapping is system dependent.

Thanks! -- Dago

**Comment by rockdaboot** [comment]
Hi Dago,

1. I'll try to remember ;-)
2. Just pushed a commit to include ./configure into dist tarball (branch 'develop). Could you give it a try and report back if that works for you ?

**Comment by rockdaboot** [comment]
I just found an older libpsl tarball... and yes, it contains ./configure script.
So, what exactly is your problem here ?
I will revert my last commit (sigh).

**Comment by dago** [comment]
Negative, the latest 0.6.2.tar.gz does not contain configure:
```
dam@unstable10s [unstable10s]:/home/dam/tmp > wget https://github.com/rockdaboot/libpsl/archive/0.6.2.tar.gz
--2015-01-20 15:29:27--  https://github.com/rockdaboot/libpsl/archive/0.6.2.tar.gz
Resolving proxy (proxy)... 192.168.1.6
Connecting to proxy (proxy)|192.168.1.6|:3128... connected.
Proxy request sent, awaiting response... 302 Found
Location: https://codeload.github.com/rockdaboot/libpsl/tar.gz/0.6.2 [following]
--2015-01-20 15:29:27--  https://codeload.github.com/rockdaboot/libpsl/tar.gz/0.6.2
Connecting to proxy (proxy)|192.168.1.6|:3128... connected.
Proxy request sent, awaiting response... 200 OK
Length: 87140 (85K) [application/x-gzip]
Saving to: '0.6.2.tar.gz'

100%[====================================================================================================================================================================================================>] 87,140       277KB/s   in 0.3s   

2015-01-20 15:29:28 (277 KB/s) - '0.6.2.tar.gz' saved [87140/87140]

dam@unstable10s [unstable10s]:/home/dam/tmp > gtar zxvf 0.6.2.tar.gz  
libpsl-0.6.2/
libpsl-0.6.2/.dir-locals.el
libpsl-0.6.2/.gitignore
libpsl-0.6.2/.travis.yml
libpsl-0.6.2/ABOUT-NLS
libpsl-0.6.2/AUTHORS
libpsl-0.6.2/COPYING
libpsl-0.6.2/LICENSE
libpsl-0.6.2/Makefile.am
libpsl-0.6.2/NEWS
libpsl-0.6.2/README
libpsl-0.6.2/README.md
libpsl-0.6.2/autogen.sh
libpsl-0.6.2/configure.ac
libpsl-0.6.2/data/
libpsl-0.6.2/data/Makefile.am
libpsl-0.6.2/data/effective_tld_names.dat
libpsl-0.6.2/data/test_psl.txt
libpsl-0.6.2/docs/
libpsl-0.6.2/docs/libpsl/
libpsl-0.6.2/docs/libpsl/Makefile.am
libpsl-0.6.2/docs/libpsl/libpsl-docs.sgml
libpsl-0.6.2/docs/libpsl/libpsl-sections.txt
libpsl-0.6.2/docs/libpsl/version.xml.in
libpsl-0.6.2/include/
libpsl-0.6.2/include/Makefile.am
libpsl-0.6.2/include/libpsl.h
libpsl-0.6.2/libpsl.pc.in
libpsl-0.6.2/po/
libpsl-0.6.2/po/Makevars
libpsl-0.6.2/po/POTFILES.in
libpsl-0.6.2/src/
libpsl-0.6.2/src/Makefile.am
libpsl-0.6.2/src/psl.c
libpsl-0.6.2/src/psl2c.c
libpsl-0.6.2/tests/
libpsl-0.6.2/tests/Makefile.am
libpsl-0.6.2/tests/test-is-cookie-domain-acceptable.c
libpsl-0.6.2/tests/test-is-public-all.c
libpsl-0.6.2/tests/test-is-public-builtin.c
libpsl-0.6.2/tests/test-is-public.c
libpsl-0.6.2/tests/test-registrable-domain.c
libpsl-0.6.2/tools/
libpsl-0.6.2/tools/Makefile.am
libpsl-0.6.2/tools/psl.c
dam@unstable10s [unstable10s]:/home/dam/tmp > ls -l 0.6.2/configure
0.6.2/configure: No such file or directory
```

**Comment by rockdaboot** [comment]
That is the tar.gz of the archive from github. It is *not* a distribution tarball (created by make dist). Thus ./configure is missing.

**Comment by dago** [comment]
I see. Is there an official release tarball? I can't find one and the debian package also seems to do autogen.sh. It would make the life for downstream packagers much easier. Thanks! -- Dago

**Comment by rockdaboot** [comment]
I just added a tarball within the github release section (special present for you ;-).
I am not sure how a packager is able to do his/her job without the complete toolchain incl. auto* tools and tools for generating docs. Tarballs are generated with some specialties from the generating system inside (though I do also see some advantages). So I personally tend to create packages from *the real sourcecode*. And that seems the way the bigger distributors go...

But anyway, thanks for bringing it up. I'll start adding tarballs for the next releases.

**Comment by cicku** [comment]
Well, being as the Fedora libpsl maintainer here, I'd say this is pretty common.

But packagers should be able to handle this:

```bash
[ -f configure ] || autoreconf -fiv
```
