### ISSUE TITLE
Libpsl on Conan Center iss under "GPL-2.0-or-later" license but on git repo it is under MIT

### ISSUE THREAD

**Issue by leoparente** [rockdaboot/libpsl#184]
Hello,

The libpsl on conan center is under GPL: https://conan.io/center/libpsl?tab=dependencies

Is that right?

**Comment by rockdaboot** [comment]
Nope, see https://github.com/rockdaboot/libpsl/blob/master/LICENSE or https://github.com/rockdaboot/libpsl/blob/master/COPYING.

Never heard of conan.io before. I don't have the resources to contact every organization that gets these things wrong :|

Anyway, thanks for reporting this.
