### ISSUE TITLE
autogen.sh does not work with autoreconf 2.69

### ISSUE THREAD

**Issue by dago** [rockdaboot/libpsl#19]
When I bootstrap manually with the command used in autogen.sh I finally get an error `GTK_DOC_USE_LIBTOOL does not appear in AM_CONDITIONAL`:
```
dam@unstable10s [unstable10s]:/home/dam/mgar/pkg/libpsl/trunk/work/solaris10-sparc/build-isa-sparcv8plus/libpsl-0.6.2 > /opt/csw/bin/autoreconf --install --force --symlink 
libtoolize: putting auxiliary files in `.'.
libtoolize: linking file `./ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIR, `m4'.
libtoolize: linking file `m4/libtool.m4'
libtoolize: linking file `m4/ltoptions.m4'
libtoolize: linking file `m4/ltsugar.m4'
libtoolize: linking file `m4/ltversion.m4'
libtoolize: linking file `m4/lt~obsolete.m4'
configure.ac:20: warning: The 'AM_PROG_MKDIR_P' macro is deprecated, and its use is discouraged.
configure.ac:20: You should use the Autoconf-provided 'AC_PROG_MKDIR_P' macro instead,
configure.ac:20: and use '$(MKDIR_P)' instead of '$(mkdir_p)'in your Makefile.am files.
gtk-doc.make:7: error: GTK_DOC_USE_LIBTOOL does not appear in AM_CONDITIONAL
docs/libpsl/Makefile.am:85:   'gtk-doc.make' included from here
docs/libpsl/Makefile.am:116: warning: '%'-style pattern rules are a GNU make extension
autoreconf: /opt/csw/bin/automake failed with exit status: 1
zsh: 19925 exit 1     /opt/csw/bin/autoreconf --install --force --symlink
```

**Comment by rockdaboot** [comment]
Regarding what I found in the net, that seems to be an issue with an outdated version of gtk-doc.
What version do you have installed ?

**Comment by rockdaboot** [comment]
Could you try this patch ?

diff --git a/configure.ac b/configure.ac
index da9936c..c04ccb7 100644
--- a/configure.ac
+++ b/configure.ac
@@ -28,6 +28,9 @@ GTK_DOC_CHECK([1.15],[--flavour no-tmpl])
 ],[
 AM_CONDITIONAL([ENABLE_GTK_DOC], false)
 ])
+m4_ifdef([GTK_DOC_USE_LIBTOOL], [], [
+AM_CONDITIONAL([GTK_DOC_USE_LIBTOOL], false)
+])
 
 #
 # enable creation of man pages

**Comment by dago** [comment]
The above patch works.

Now the only warnings left are
```
configure.ac:20: warning: The 'AM_PROG_MKDIR_P' macro is deprecated, and its use is discouraged.
configure.ac:20: You should use the Autoconf-provided 'AC_PROG_MKDIR_P' macro instead,
configure.ac:20: and use '$(MKDIR_P)' instead of '$(mkdir_p)'in your Makefile.am files.
docs/libpsl/Makefile.am:116: warning: '%'-style pattern rules are a GNU make extension
```

I do not have gtk-doc installed.

**Comment by rockdaboot** [comment]
Please have a look if m4/gtk-doc.m4 exists. If you don't have gtk-doc installed, this file should not be there. Hmm, also gtk-doc.make should be empty (autogen.sh creates an empty one if gtkdocize does not exist).

**Comment by rockdaboot** [comment]
Sorry, Dago. Back to zero.

You said
"When I bootstrap manually with the command used in autogen.sh I finally get an error GTK_DOC_USE_LIBTOOL does not appear in AM_CONDITIONAL:"

You somehow generated gtk-doc.make before on a system where gtkdocize (from gtk-doc) was available. Than you removed gtk-doc (or worked on a system without gtk-doc) and tried to run autoreconf manually. But you forgot to recreate gtk-doc.make which is done in ./autogen.sh in case gtk-doc is not installed. This likely will break things during 'make'. And this is the reason why providing a tarball is not a good idea ! At least we need the above work-around in configure.ac to help people without gtk-doc installed. But the proper way would be to generate the library from git.

Thanks for testing and improving the build procedure.
