### ISSUE TITLE
can not link my app anymore

### ISSUE THREAD

**Issue by hbenrico** [rockdaboot/libpsl#198]
Hello,

after an msys2 packages upgrade, can not link my application anymore

ld.lld: error: undefined symbol: __declspec(dllimport) uninorm_nfkc
>>> referenced by libpsl.a(psl.c.obj):(psl_str_to_utf8lower)
>>> referenced by libpsl.a(psl.c.obj):(psl_str_to_utf8lower)

thanks in advance 
Enrico

**Comment by rockdaboot** [comment]
libpsl doesn't use this function directly, but only via `u8_tolower((uint8_t *)str, len, 0, UNINORM_NFKC, NULL, &len)`.

I would check that libunistring has been updated as well.
If the error persists, raise an issue against the libunistring package and/or ask on the mailing list bug-libunistring@gnu.org.
