### ISSUE TITLE
meson setup  fails with git code: 'public_suffix_list.dat does not exist'

### ISSUE THREAD

**Issue by vtorri** [rockdaboot/libpsl#199]
on Windows (msys2 + mingw-w64), `meson builddir` reports:

```
src/meson.build:3:0: ERROR: File E:/Documents/programmes_x64/msys2/home/vtorri/gitroot_64/libpsl_vtorri/list/public_suffix_list.dat does not exist.
```

**Comment by rockdaboot** [comment]
`list` is a git submodule. I guess you didn't initialize it - that's what `./autogen.sh` does for you. You also could use `--recursive` when clonign with git.

I amended the instructions, as they were a bit unclear.

Thanks for pointing this out.
