### ISSUE TITLE
Windows: warning with localtime_s in tools/psl.c

### ISSUE THREAD

**Issue by vtorri** [rockdaboot/libpsl#201]
in tools/psl.c line 97 : 

```
../tools/psl.c: In function 'time2str':
../tools/psl.c:97:34: warning: comparison between pointer and integer
   97 |         if (localtime_r(&t, &tm) != NULL)
      |                                  ^~
```

This is because on `localtime_s()` is used and this function does not return a pointer, but an `errno_t`:

https://learn.microsoft.com/en-us/cpp/c-runtime-library/reference/localtime-s-localtime32-s-localtime64-s?view=msvc-170

**Comment by rockdaboot** [comment]
We have this since https://github.com/rockdaboot/libpsl/pull/195.
Feel free to come up with a fix, or maybe @fanc999 ?

**Comment by vtorri** [comment]
duplicate

**Comment by fanc999** [comment]
Thanks @vtorri!

**Comment by tp-m** [comment]
It would be great if you could tag another bug-fix release one of these days :)
