### ISSUE TITLE
0.21.2 exports two symbols without `psl_` prefix

### ISSUE THREAD

**Issue by dkg** [rockdaboot/libpsl#205]
I'm trying to get 0.21.2 in shape for debian packaging, and i notice that the shared object from 0.21.2 exports two symbols that  which don't have a `psl_` prefix:

- `GetUtfMode`
- `LookupStringInFixedSet`

I'm assuming that these are only accidentally exposed.  I haven't been able to trace why they're being exposed now, but they were not exposed in 0.21.1.

**Comment by dkg** [comment]
i notice a6397a0d62992d5e73be9071c86a746c32fdac4e, which looks relevant, but it happened before 0.21.1 (before 0.20.2, actually) 

So it's possible that this is due to some sort of toolchain issue, i'm not sure.

I do notice that if i try to build from the git tags directly with `./autogen.sh && ./configure && make` that  i cannot deliberately replicate the problem.  So maybe there are some options that debian build infrastructure are using that make it possible to accidentally export these symbols?

**Comment by eli-schwartz** [comment]
It seems it is conditional on gnulib providing `gl_VISIBILITY` which causes configure to test whether -fvisibility=hidden works, and if so, provide that as CFLAGS_VISIBILITY. Building from a freshly autoreconf'ed source tree I see this in the ./configure output:

```
./configure: 13558: gl_VISIBILITY: not found
```

**Comment by eli-schwartz** [comment]
#206 solves this for meson, as it seems to be an oversight that it is missing there.

**Comment by dkg** [comment]
i agree with this assessment, @eli-schwartz  -- thanks for looking into it so promptly!  it looks to  me like the gnulib macro `m4/visibility.m4` isn't included in the git repository, which is why `gl_VISIBILITY` is missing.  I'll prepare a patch for that, since i believe the expectation for gnulib is that it is copied into projects where it is used.

**Comment by eli-schwartz** [comment]
That was my assumption too -- I had to download a copy from gnulib.git with `wget` and copy it into place, after which it worked, but I have no clue how gnulib works in general.
