### ISSUE TITLE
Windows 10: is it better to use icu provide with Windows, or compile and use the latests icu code ?

### ISSUE THREAD

**Issue by vtorri** [rockdaboot/libpsl#208]
on my computer, icu has been installed by Windows in 2021, but ICU has released more recent versions. Which ICU version users should use ?

**Comment by rockdaboot** [comment]
Normally it doesn't matter as long as your ICU isn't too old.
You can check yourself whether the [PSL](https://github.com/publicsuffix/list/blob/master/public_suffix_list.dat) contains any Unicode characters that aren't covered by the pre-installed ICU. But I would be very surprised.
