### ISSUE TITLE
'make install' doesn't install psl-make-dafsa, but its man file

### ISSUE THREAD

**Issue by TurtleWilly** [rockdaboot/libpsl#212]
```
$ ./configure --prefix=/usr/local/targetdirectory/libpsl/0.21.2 --enable-man …
$ make
$ make install
```

```
$ cd /usr/local/targetdirectory/libpsl/0.21.2
$ find . -iname '*dafsa*'
./share/man/man1/psl-make-dafsa.1
```

The man file for `psl-make-dafsa` gets installed, but the script itself doesn't get installed. It should either be fixed in one way (do not install the man file) or the other (also install `psl-make-dafsa`). Personally I would go the second route as the script can be useful in auto-updating scripts for "public-suffix-list.dat" in the configured distfile location.

**Comment by rockdaboot** [comment]
Thanks. I made a change to install `psl-make-dafsa`.
