### ISSUE TITLE
Make the IDN conversions at generation time?

### ISSUE THREAD

**Issue by bagder** [rockdaboot/libpsl#220]
The way libpsl supports IDN in the API adds complicated dependencies to libpsl that lots of users do not need.

In the @curl project for example we like libpsl for its lookup, but we already do the punycode conversion ourselves in an earlier stage.

I would love an API that *only* accepts ascii/punycode and that does the IDN-conversion at the time it generates the lookup data. It would also greatly simplify the run-time parts.

I realize this would be a major API change but IMHO, one that would make this lib a more powerful one.

**Comment by rockdaboot** [comment]
Hey Daniel,

I am not sure I fully understand the intention.

I assume that libpsl package maintainers are (normally) using one of the IDN libraries as runtime dependency. It means that even with an API that *only* supports ascii/punycode, the IDN library still is linked into libcurl as an indirect dependency.

What you already can do today, if the whole build process is under your control, is using the `--disable-runtime` configure option. The lookup data (I assume DAFSA) is generated with punycode (this is the standard configuration). This allows you to use the API with punycode only - there is no need to use utf-8.
The important thing is that your unicode/uft-8 strings are normalized before converting into punycode. E.g. umlauts like 'ü' have different byte representations in unicode/utf-8 and these end up in different ascii representations. And only one of them is, the normalized one, is contained in the PSL lookup data.

Following https://github.com/curl/curl-for-win/issues/63, it seems there are some misunderstandings in how libpsl works and how the lookup data is generated. You have all degrees of freedom when you control the build. Of course, I also might misunderstand some comments in the issue (they are not all 100% clear to me).

**Comment by rockdaboot** [comment]
Issue solved, see https://github.com/curl/curl-for-win/issues/63#issuecomment-1890987014

**Comment by bagder** [comment]
I still wish libpsl would not do IDN at run-time. I think it would make it a much better, smaller, simpler and more focused library. But yes, that's just my opinion.

**Comment by rockdaboot** [comment]
It doesn't do any IDN when opted out. The hole lib then is just 17k, most of it ELF overhead, not code.
If you take a look at the curl issue, you'll see the version string is `libpsl/0.21.5 (no IDNA support)`.
