### ISSUE TITLE
Signed tarballs used to be available under `releases/download/v0.21.4/libpsl-0.21.4.tar.lz{,.sig})`

### ISSUE THREAD

**Issue by BrianInglis** [rockdaboot/libpsl#225]
Tarballs and sigs:
`https://github.com/rockdaboot/libpsl/releases/download/v0.21.4/libpsl-0.21.4.tar.lz{,.sig}`
Will they be available for this release?

**Comment by rockdaboot** [comment]
Thanks for the heads up, Brian.

0.21.5 is released with all those assets.
