### ISSUE TITLE
Request broader platform support for libpsl

### ISSUE THREAD

**Issue by rsbeckerca** [rockdaboot/libpsl#229]
I am trying to build libpsl on a POSIX platform other than Linux and it has issues when not using gcc. I am limited to c99. The initial build problems are as follows:

```
  CC       libpsl_la-psl.lo
        struct in6_addr addr6;
                        ^
"/home/randall/libpsl-0.21.5/src/psl.c", line 1611: error(163): incomplete type is not allowed

        return inet_pton(AF_INET, hostname, &addr) || inet_pton(AF_INET6, hostname, &addr6);
               ^
"/home/randall/libpsl-0.21.5/src/psl.c", line 1613: error(114): identifier "inet_pton" is undefined

2 errors detected in the compilation of "psl.c".
```
I cannot find `inet_pton` outside of very limited Linux distros. If is not in a common library. The incomplete type is probably just a missing include of in6.h. I can help with that, but intergrating with `inet_pton` is problematic.

**Comment by rsbeckerca** [comment]
I fixed the compile issue - it as actually simple - see commit [475e238](https://github.com/rsbeckerca/libpsl/commit/475e23812ea318c4eba996b2f41e6e28c77ddafe) - but need DLL support, which is not according to what configure wants. I need to specify `-Wshared`.

**Comment by rockdaboot** [comment]
This issue has been fixed in git master.
