### ISSUE TITLE
Solaris does not have bits/stat.h

### ISSUE THREAD

**Issue by dago** [rockdaboot/libpsl#32]
The build on Solaris breaks because of the inclusion of `<bits/stat.h>` which does on exist. Just taking out the include works on Solaris.

**Comment by rockdaboot** [comment]
I have no idea, how that made it into the source. Will check OpenBSD tomorrow, but I guess it was a mistake. Thanks for pointing out !

**Comment by dago** [comment]
This seems to be the only issue left.

**Comment by rockdaboot** [comment]
Fix pushed.
I built the latest stuff from branch 'develop' on the Solaris built farm (on unstable10x, unstable11x) without problems, the test suite succeeds.
