### ISSUE TITLE
Failing test-registrable-domain

### ISSUE THREAD

**Issue by dago** [rockdaboot/libpsl#33]
One test is failing on Solaris:
```
FAIL: test-registrable-domain
=============================

have 6265 suffixes and 9 exceptions
Failed to open ../list/tests/test_psl.txt
Summary: 1 out of 9 tests failed
FAIL test-registrable-domain (exit status: 1)
```

The file `test_psl.txt` does not exist in the repo.

**Comment by rockdaboot** [comment]
list/ is a git submodule. Could you 'rm -rf list' and ./autogen.sh && configure && make again ?
test_psl.txt is definitely part of the publicsuffix/list repo. It should be there.

**Comment by dago** [comment]
Forgot to set the proxy during `autogen.sh` which resulted in the submodules not being pulled in. Sorry for the noise.
