### ISSUE TITLE
Make a distinction been ICANN and PRIVATE entries

### ISSUE THREAD

**Issue by sleevi** [rockdaboot/libpsl#36]
Since libpsl is meant to include mitigations for super-certificates, it is arguably necessary to make a distinction between the ICANN and PRIVATE sections within the PSL.

For example, `appspot.com` is in the PSL, but `*.appspot.com` is a valid certificate (controlled by Google), and should not be rejected, while `com`, also in the PSL, should not allow `*.com`

As implemented by Chromium, some restrictions - such as certificates - only apply to the ICANN portion of the PSL, while other restrictions - such as cookies - apply for the entire PSL. This replaces the previous heuristic, which was similar to Firefox's, which was "require two dots" - which works for `.com`, but fails for `.co.uk`.

As presently implemented, libpsl is not safe/suitable to use to prevent such super-certificates, due to the inability to distinguish via the built-in.

**Comment by rockdaboot** [comment]
I just found the ICANN and the PRIVATE sections (wasn't aware of them before).
I'll extend the API in the next release.

> For example, appspot.com is in the PSL, but *.appspot.com is a valid certificate (controlled by Google), and should not be rejected, while com, also in the PSL, should not allow *.com

You say 'com' the the PSL means in fact '*.com' ? In this case, libpsl is wrong about that right now. From my understanding:
* appspot.com is a PS (appspot.com rule)
* *.appspot.com is not (no *.appspot.com rule)
* com is a PS (com rule, also it is a TLD)
* xyz.com is not a PS (no rule *.com exists)

Are you wrong or am I ?

**Comment by sleevi** [comment]
You're wrong.

I said 'com' was in the PSL, which makes a wildcard certificate (*.com) not
valid.

appspot.com is also in the PSL, but *.appspot.com IS valid. This is where
the ICANN vs PRIVATE portions come into plays.

This isn't an exact match for what the Baseline Requirements
permit/prohibit CAs to issue, but it is a more secure heuristic than simply
requiring two dots for wildcard certs.

Since you mentioned wildcard cert handling was a potential use case for
libpsl, I figured I would highlight the minimum necessary to
safely/securely support that, which is distinguishing those two cases.

**Comment by rockdaboot** [comment]
Ok, some thoughts, please correct me if I am wrong.
* private and ICANN entries are mutually exclusive -> having an internal 'private/icann' flag is ok
* we need two more functions like psl_is_public_suffix_icann(psl, domain) and psl_is_public_suffix_private(psl, domain)
* with this approach we might need more _icann and _private versions of other functions.

Alternatively, one could switch the whole API to 'PRIVATE', 'ICANN' or 'ANY' (default) with a single function like psl_set_range(psl, PRIVATE | ICANN | ANY). Maybe this will be the most backward compatible way.

WDYT ? (Something missing that you would like to see ?)

This would be relatively easy to implement, before I start with DAFSA (that turns a few things internally upside down).

**Comment by sleevi** [comment]
> *  private and ICANN entries are mutually exclusive -> having an internal 'private/icann' flag is ok

Ish? I mean, it's possible to imagine a brand TLD of .brand and then a private entry of *.brand, so you run into some element of risk there.

As far as what the PSL actually guarantees, no - this isn't guaranteed by the PSL (it doesn't guarantee that rules won't repeat, although de facto they don't).

Certainly, within Chromium and as I've seen in other implementations, we get away with a flag (private vs not-private; not implying ICANN, just not-private), so if that's how you see it, that's a reasonable interpretation.

> *  we need two more functions like psl_is_public_suffix_icann(psl, domain) and psl_is_public_suffix_private(psl, domain)

So to make sure I understand the symmetry with the flag alternative you propose:
 *  psl_is_public_suffix(psl, domain) - equivalent to ANY
 *  psl_is_public_suffix_icann(psl, domain) - equivalent to ICANN
 *  psl_is_public_suffix_private(psl, domain) - equivalent to PRIVATE

The problem with that is your API calls grow rapidly if the PSL adds any more types. I'm not sure what that would be, but I'm also not sure it wouldn't happen.

> single function like psl_set_range(psl, PRIVATE | ICANN | ANY)

Doesn't that make the code more thread hostile? Won't each thread need to have their own `psl` structure in order to safely query across threads? Won't that increase memory overheads?

**Comment by rockdaboot** [comment]
Thanks for your thoughts.
I can only design the API on things I know about the PSL. So any information about possible future plans (e.g. adding more types) helps me to make the right API decisions. I am not sure if Chromium does the right thing, when we consider a domain being in ICANN *and* PRIVATE section (in the future). The current DAFSA structure has one unused result bit that could be used as ICANN flag - so ICANN and PRIVATE would be possible. But for more types, the DAFSA structure has to be extended.

> >    single function like psl_set_range(psl, PRIVATE | ICANN | ANY)

> Doesn't that make the code more thread hostile? Won't each thread need to have their own psl structure in order to safely query across threads? Won't that increase memory overheads?

It would be just the 'head' structure that would be unique to each thread (a handful of bytes allocated). But you are right, we can use sharable structures, returned via a new function psl_builtin2(PRIVATE | ICANN | ANY).

**Comment by rockdaboot** [comment]
Finally, I just added a new function psl_is_public_suffix2() with an additional 'type' argument to limit the check to ICANN, PRIVATE (or ANY). The change is in branch 'develop'.

**Comment by rockdaboot** [comment]
Released as libpsl-0.12.0
