### ISSUE TITLE
Improve travis integration

### ISSUE THREAD

**Issue by darnir** [rockdaboot/libpsl#38]
There are a couple of points here:

1. Use the new container based architecture: These jobs fire faster and support installing packages without explicitly calling apt ourselves. Also, the recommended way to use Travis now.
2. Split the three different runtimes into a build matrix: This will provide faster results, and tell us clearly when a certain runtime breaks. The build matrix would be 6 simultaneous builds for 3 runtimes and 2 compiler options
3. The Travis docs state that the virtual machines have 1.5-2 cores each. So maybe we can change the value of -j to 2?

I have made the first change locally. But the container based architecture doesn't yet provide libidn2-0 packages. I've opened an issue for that. As soon as they add these packages, I'll open another pull request here.

**Comment by rockdaboot** [comment]
Nice, Darshit !
Use -j value as you find it appropriate (I have N=(#cores + 1) in mind, but 2 is perfectly ok for me).
I am looking forward to seeing your pull request.
