### ISSUE TITLE
Compilation problem

### ISSUE THREAD

**Issue by FrIcE** [rockdaboot/libpsl#44]
When trying compile latest 0.12.0 version, i have next issue:
psl.c:839:53: error: use of undeclared identifier 'kDafsa'
                size_t dafsa_size = psl == &_builtin_psl ? sizeof(kDafsa) : psl->dafsa_size;
                                                                  ^
psl.c:840:55: error: use of undeclared identifier 'kDafsa'; did you mean 'dafsa'?
                const unsigned char *dafsa = psl == &_builtin_psl ? kDafsa : psl->dafsa;
                                                                    ^~~~~~
                                                                    dafsa

I use next environment:

FreeBSD j64.devel.local 10.2-STABLE FreeBSD 10.2-STABLE #0: Mon Jan  4 02:57:34 YEKT 2016     ***  amd64

FreeBSD clang version 3.4.1 (tags/RELEASE_34/dot1-final 208032) 20140512
Target: x86_64-unknown-freebsd10.2
Thread model: posix

Content of src/suffixes_dafsa.c file:

/* automatically generated by psl2c (punycode generated with libicu/56.1) */
static time_t _psl_file_time = 1451134939;
static int _psl_nsuffixes = 6299;
static int _psl_nexceptions = 9;
static int _psl_nwildcards = 28;
static const char _psl_sha1_checksum[] = "";
static const char _psl_filename[] = "/ports/www/libpsl/work/libpsl-0.12.0/list/public_suffix_list.dat";

**Comment by rockdaboot** [comment]
./autogen.sh should clearly check if you have python installed.
That's what seems missing - I tested with python3 here.

The new version needs src/make_dafsa.py being run (a python script).
Does this help you ?

**Comment by darnir** [comment]
In fact in a clean environment, I'm seeing the same issue on my Arch Linux
systems.

```
make maintainer-clean
./autogen.sh
./configure --enable-builtin=libicu
make
```

returns the same errors.

On 4 January 2016 at 17:03, Tim Rühsen <notifications@github.com> wrote:

> ./autogen.sh should clearly check if you have python installed.
> That's what seems missing - I tested with python3 here.
>
> The new version needs src/make_dafsa.py being run (a python script).
> Does this help you ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rockdaboot/libpsl/issues/44#issuecomment-168716547>.
>



-- 
Thanking You,
Darshit Shah

**Comment by FrIcE** [comment]
Just installed Python and all was fine (even without running autogen.sh).
Checked with both 2.7 and 3.5 branches.

Thanks.
