### ISSUE TITLE
psl2c segfault

### ISSUE THREAD

**Issue by DannyThomas** [rockdaboot/libpsl#47]
RHEL7  gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-4)

Building libpsl version 0.12.0, on host kragle at 11-Feb-2016 19:22 from:
 libpsl-libpsl-0.12.0.tar.gz
-----
  0.0: fetching & unpacking libpsl-libpsl-0.12.0.tar.gz
  0.0: FYI no patches were applied
  0.0:   /bin/bash# cd /opt/uq.cis.work/build.libpsl/libpsl-libpsl-0.12.0
  0.0: The 'fatal: Not a git repository' msgs don't seem to be a problem
  0.0:   /bin/bash# ./autogen.sh 
fatal: Not a git repository (or any parent up to mount point /opt)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
fatal: Not a git repository (or any parent up to mount point /opt)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
configure.ac:32: warning: The 'AM_PROG_MKDIR_P' macro is deprecated, and its use is discouraged.
configure.ac:32: You should use the Autoconf-provided 'AC_PROG_MKDIR_P' macro instead,
configure.ac:32: and use '$(MKDIR_P)' instead of '$(mkdir_p)'in your Makefile.am files.
configure.ac:11: installing './ar-lib'
configure.ac:13: installing './config.guess'
configure.ac:13: installing './config.sub'
configure.ac:4: installing './install-sh'
configure.ac:4: installing './missing'
docs/libpsl/Makefile.am:119: warning: '%'-style pattern rules are a GNU make extension
src/Makefile.am:24: warning: compiling 'psl2c.c' with per-target flags requires 'AM_PROG_CC_C_O' in 'configure.ac'
src/Makefile.am: installing './depcomp'
parallel-tests: installing './test-driver'
 19.1:   /bin/bash# export CC=/usr/bin/gcc
 19.1:   /bin/bash# export CFLAGS=-O2 -m64 -mtune=generic -g -pipe -Wall -fexceptions --param=ssp-buffer-size=4 -fstack-protector-strong -grecord-gcc-switches
 19.1:   /bin/bash# export CPPFLAGS=-O -D_FORTIFY_SOURCE=2
 19.1:   /bin/bash# export PKG_CONFIG_PATH=/opt/uq.cis.built/0-pkg-config
 19.1:   /bin/bash# export LDFLAGS=-L/opt/uq.cis.built/libicu4c/current/lib -Wl,-rpath=/opt/uq.cis.built/libicu4c/current/lib
 19.1:   /bin/bash# ./configure --prefix=/opt/uq.cis.built/libpsl  --with-psl-file=/opt/uq.cis.etc/public_suffix_list.dat
 24.7:   /bin/bash# make
make[2]: *** [suffixes_dafsa.c] Segmentation fault
make[2]: *** Deleting file `suffixes_dafsa.c'

it doesn't segfault until it's doing something
[root@kragle src]# ./psl2c
Usage: psl2c [--binary] <infile> <outfile>
  <infile>  is the 'public_suffix_list.dat', lowercase UTF-8 encoded
  <outfile> is the the filename to be generated from <infile>
  --binary  Generate binary DAFSA output (default: C code for psl.c)
[root@kragle src]# ./psl2c /opt/uq.cis.etc/public_suffix_list.dat /tmp/psl.out
Segmentation fault
[root@kragle src]# ./psl2c --binary /opt/uq.cis.etc/public_suffix_list.dat /tmp/psl.out
Segmentation fault
[root@kragle src]#

**Comment by rockdaboot** [comment]
psl2c is an 'internal' tool, not for general use ;-)

What is your intention ?

**Comment by DannyThomas** [comment]
On 11 Feb 2016, at 11:40 PM, Tim Rühsen <notifications@github.com<mailto:notifications@github.com>> wrote:


psl2c is an 'internal' tool, not for general use ;-)

What is your intention ?

it is being invoked by make
the only reason I ran it manually was to provide
some information for the bug report

**Comment by DannyThomas** [comment]
public_suffix_list.dat was downloaded from Mozilla yesterday
/tmp/psl.out exists but is empty

the  PKG_CONFIG_PATH and LDFLAGS are so it finds the
latest libicu4c I built.

I couldn't see how make_dafsa.py found python because
the man page refers to gnu's texinfo, but anyway
# `which python` --version
Python 2.7.5

[root@kragle src]# valgrind ./psl2c /opt/uq.cis.etc/public_suffix_list.dat /tmp/psl.out
==122266== Memcheck, a memory error detector
==122266== Copyright (C) 2002-2013, and GNU GPL'd, by Julian Seward et al.
==122266== Using Valgrind-3.10.0 and LibVEX; rerun with -h for copyright info
==122266== Command: ./psl2c /opt/uq.cis.etc/public_suffix_list.dat /tmp/psl.out
==122266== 
==122266== Invalid read of size 4
==122266==    at 0x40164E: _print_psl_entries_dafsa (psl2c.c:154)
==122266==    by 0x40164E: main (psl2c.c:272)
==122266==  Address 0x14 is not stack'd, malloc'd or (recently) free'd
==122266== 
==122266== 
==122266== Process terminating with default action of signal 11 (SIGSEGV)
==122266==  Access not within mapped region at address 0x14
==122266==    at 0x40164E: _print_psl_entries_dafsa (psl2c.c:154)
==122266==    by 0x40164E: main (psl2c.c:272)
==122266==  If you believe this happened as a result of a stack
==122266==  overflow in your program's main thread (unlikely but
==122266==  possible), you can try to increase the size of the
==122266==  main thread stack using the --main-stacksize= flag.
==122266==  The main thread stack size used in this run was 8388608.
==122266== 
==122266== HEAP SUMMARY:
==122266==     in use at exit: 2,340,832 bytes in 4 blocks
==122266==   total heap usage: 12 allocs, 8 frees, 10,664,472 bytes allocated
==122266== 
==122266== LEAK SUMMARY:
==122266==    definitely lost: 40 bytes in 1 blocks
==122266==    indirectly lost: 2,339,656 bytes in 1 blocks
==122266==      possibly lost: 0 bytes in 0 blocks
==122266==    still reachable: 1,136 bytes in 2 blocks
==122266==         suppressed: 0 bytes in 0 blocks
==122266== Rerun with --leak-check=full to see details of leaked memory
==122266== 
==122266== For counts of detected and suppressed errors, rerun with: -v
==122266== ERROR SUMMARY: 1 errors from 1 contexts (suppressed: 1 from 1)
Segmentation fault


[psl2c.c.txt](https://github.com/rockdaboot/libpsl/files/126921/psl2c.c.txt)
[config.h.txt](https://github.com/rockdaboot/libpsl/files/126922/config.h.txt)

**Comment by DannyThomas** [comment]
oops, I'd downloaded the html wrapped version from their repo
psl2c is much happier.

**Comment by rockdaboot** [comment]
Hmmm, I'll give a try. psl2c could be a bit more verbose ... and shouldn't crash at all.
