### ISSUE TITLE
/usr/bin/psl should only link to libpsl, not to any of the IDN libraries

### ISSUE THREAD

**Issue by dkg** [rockdaboot/libpsl#51]
currently, tools/psl gets built using the same LDFLAGS as libpsl.so.  This includes (e.g.) -licuuc and -licudata (from pkg-config from libicu).

However, psl shouldn't need that linkage, since it calls none of the symbols in (e.g.) libicu directly.

adjusting the build system to ensure that psl only links against libpsl would be better.

**Comment by rockdaboot** [comment]
I am not aware of any difference on a GNU/Linux toolchain when linking dynamically - the linker should recognize it and handle it gracefully. What exactly is the problem ?
And with static linking, you'll need LDFLAGS.
What about environments like Windows ?

**Comment by dkg** [comment]
On Tue 2016-07-05 16:02:12 -0400, Tim Rühsen wrote:
> I am not aware of any difference on a GNU/Linux toolchain when linking
> dynamically - the linker should recognize it and handle it
> gracefully. What exactly is the problem ?

sure, most linkers recognize it and handle it gracefully, but the
linkage is still spurious.  It also means that if a user installs a
version of libpsl that is linked to IDN library X, but /usr/bin/psl is
still linked to library Y, both libraries will be loaded into the
runtime process.

> And with static linking, you'll need LDFLAGS.
> What about environments like Windows ?

I didn't mean to get into static linking or Windows -- but when linking
statically, you're presumably already linking statically to a static
libpsl, which itself would already be statically linked, so again, the
explicit linkage to libicu is superfluous.

        --dkg

**Comment by rockdaboot** [comment]
Basically we already do what it that way. There was just a bug when using libicu + pkg-config.
Fixed in 'develop' now.
BTW, it was the LIBS variable.
And a static library does not include all external references - these still have to be resolved by explicitly mentioning the needed libraries during the link step. Maybe libtool cares for that ? I am also not into static linking... these days were 20 years ago ;-)
