### ISSUE TITLE
Unbounded use of alloca

### ISSUE THREAD

**Issue by daurnimator** [rockdaboot/libpsl#58]
There are places in your code that use a potentially unbounded `alloca`.

  - https://github.com/rockdaboot/libpsl/blob/0486815dbdca773bdae1ee63b042b73a07bc760f/src/psl.c#L527
  - https://github.com/rockdaboot/libpsl/blob/0486815dbdca773bdae1ee63b042b73a07bc760f/src/psl.c#L1608
  - https://github.com/rockdaboot/libpsl/blob/0486815dbdca773bdae1ee63b042b73a07bc760f/src/psl.c#L1609
  - https://github.com/rockdaboot/libpsl/blob/0486815dbdca773bdae1ee63b042b73a07bc760f/src/psl.c#L1610

**Comment by daurnimator** [comment]
In `_utf8_to_utf32` there are now return paths that do not `free`. e.g. https://github.com/rockdaboot/libpsl/blob/10f7b5fe7c3edfd241908b41a4c6dcaf3b0033ea/src/psl.c#L556

**Comment by rockdaboot** [comment]
Thanks, good point. Just removed the memory allocations.
