### ISSUE TITLE
Don't use C identifiers that start with underscore (_)

### ISSUE THREAD

**Issue by daurnimator** [rockdaboot/libpsl#61]
From http://pubs.opengroup.org/onlinepubs/009695399/functions/xsh_chap02_02.html
> With the exception of identifiers beginning with the prefix _POSIX_, all identifiers that begin with an underscore and either an uppercase letter or another underscore are always reserved for any use by the implementation.

**Comment by rockdaboot** [comment]
Regarding the citation, `_[A-Z]...` and `__...` should not be used. `_[a-z]...` is all right.
[And btw, libpsl is C89 and not really POSIX (in the beginning of this project, someone insisted on it being C89).]

**Comment by daurnimator** [comment]
It's not just a POSIX thing, see also e.g. gcc, from https://www.gnu.org/software/libc/manual/html_node/Reserved-Names.html:
> reserved names include all external identifiers (global functions and variables) that begin with an underscore (‘_’) and all identifiers regardless of use that begin with either two underscores or an underscore followed by a capital letter are reserved names.

But yes, it looks like your usage may be within the allowed usage (they're all non-external).

> [And btw, libpsl is C89 and not really POSIX (in the beginning of this project, someone insisted on it being C89).]

IIRC, in C89 all declarations must be at the top of a function, so e.g. https://github.com/rockdaboot/libpsl/blob/9e1ca81be4b1d658ac5a7a5f312d5ada3a9ba6b0/src/psl.c#L596 isn't permitted.
Not that I think full C89 compliance is worth it any more.

**Comment by rockdaboot** [comment]
> But yes, it looks like your usage may be within the allowed usage (they're all non-external).

Yes, and I use it with several projects. You'll find recommendations to use underscore for local (static) objects if you search the web. And I like it.

> IIRC, in C89 all declarations must be at the top of a function
No, at the top of a block. Or more exactly you must not mix declarations and code (within a block).
-std=c89 will complain if you do (used in contrib/check-hard script).
