### ISSUE TITLE
OOB in _domain_to_punycode

### ISSUE THREAD

**Issue by daurnimator** [rockdaboot/libpsl#62]
`input` is only 256 bytes (https://github.com/rockdaboot/libpsl/blob/6cfb33e5308d95f787e574f13c2b29d6fe27d42a/src/psl.c#L592)

There are several ways that libpsl may read or write beyond the end of that array.

This is _not_ an error with in the current code as the 3rd parameter to `_domain_to_punycode` is always 128 at [the single call site](https://github.com/rockdaboot/libpsl/blob/6cfb33e5308d95f787e574f13c2b29d6fe27d42a/src/psl.c#L778). However this assumption is very easy to break if `_domain_to_punycode` was to be used from elsewhere.

**Comment by daurnimator** [comment]
Aside: `_domain_to_punycode` doesn't do unicode normalisation (which is a required part of punycode conversion). Perhaps you should drop support for it if neither libicu or libidn are installed?

**Comment by rockdaboot** [comment]
> Perhaps you should drop support for it if neither libicu or libidn are installed?

Perhaps yes. The idea was to support a limited set of domains - a use case that isn't very unlikely.
I am unsure and leave this open for further discussion.

**Comment by rockdaboot** [comment]
Since we have continuous fuzzing to coverthat area of code we can meanwhile be sure that there is no hole. Thanks for the heads up !
