### ISSUE TITLE
autoconf warnings

### ISSUE THREAD

**Issue by daurnimator** [rockdaboot/libpsl#66]
```
libtoolize: linking file 'm4/lt~obsolete.m4'
configure.ac:32: warning: The 'AM_PROG_MKDIR_P' macro is deprecated, and its use is discouraged.
configure.ac:32: You should use the Autoconf-provided 'AC_PROG_MKDIR_P' macro instead,
configure.ac:32: and use '$(MKDIR_P)' instead of '$(mkdir_p)'in your Makefile.am files.
```

Lots of warnings about gtk-doc.make using non-portable constructs. e.g. 
```
docs/libpsl/Makefile.am:85:   'gtk-doc.make' included from here
gtk-doc.make:206: warning: GTK_DOC_V_PDF_$(AM_DEFAULT_VERBOSITY: non-POSIX recursive variable expansion
```

**Comment by daurnimator** [comment]
> Lots of warnings about gtk-doc.make using non-portable constructs. 

This can be fixed with the `-Wno-portability` flag:

```diff
diff --git a/configure.ac b/configure.ac
index 2653141..0465e20 100644
--- a/configure.ac
+++ b/configure.ac
@@ -1,7 +1,7 @@
 
 AC_INIT([libpsl], [0.14.0], [tim.ruehsen@gmx.de], [libpsl], [https://github.com/rockdaboot/libpsl])
 AC_PREREQ([2.59])
-AM_INIT_AUTOMAKE([1.10 -Wall no-define foreign])
+AM_INIT_AUTOMAKE([1.10 -Wall -Wno-portability no-define foreign])
 
 # Generate two configuration headers; one for building the library itself with
 # an autogenerated template, and a second one that will be installed alongside
```

**Comment by rockdaboot** [comment]
The deprecation warning is pulled in via gettext... changing m4/intl.m4 and m4/po.m4 fixes it.
This vanishes when I specify gettext 0.19.1 in configure.ac (0.19.8 installed here).
But this would break autoreconf on systems with a lower gettext version.

For now, I remove -Wall from automake options, since 'foreign' already sets -Wno-portability.

**Comment by darnir** [comment]
Gettext 0.19.1 came out over 2 years ago. Are there any systems using libpsl that are using such old libraries?

Maybe we can write an ugly conditional in configure.ac to check the gettext version and use the right one
