### ISSUE TITLE
Function that automatically picks up newer data

### ISSUE THREAD

**Issue by daurnimator** [rockdaboot/libpsl#73]
Suggested by @KellerFuchs

Add a function (perhaps named `psl_default`).
If `psl_builtin_outdated()` it should return `psl_load_file(psl_builtin_filename())`
Otherwise, return `psl_builtin()`
This might be useful if some distro ships a data package which updates a file in the right place.

**Comment by rockdaboot** [comment]
The way to go (with libpsl 0.15+) is trying to load a given file (e.g. on Debian it is /usr/share/publicsuffix/public_suffix_list.dafsa from package publicsuffix). That file is hard-coded or a ./configure option (like for wget). Only if that fails, the application should fall back to the algorithm that you suggest (done for wget).

Why should the application implement that code and not libpsl ?
The app might want to tell the user that something is missing or should be changed for optimal functionality. Your suggestion just returns a valid psl pointer... of course psl_default() could take a pointer to a result, but than it starts to become ugly (IMO).

**Comment by KellerFuchs** [comment]
@rockdaboot The application can anyway do that test, simply by checking how old the data it is using is.

The point there is to offer a function which does the right thing by default, if possible.  Otherwise, the likeliest outcome is that most applications will silently use obsolete data.

**Comment by rockdaboot** [comment]
OK, but then the builtin filename should point to the DAFSA representation (e.g. on Debian it currently points to the original TEXT file - reading it introduces lot's of processing).
I'll have a look in the next days.

**Comment by rockdaboot** [comment]
Please check/review branch 'psl_latest' if that fits your needs.
If your distribution has a package with PSL data, specify that PSL file with ./configure --with-psl-distfile=<filename> (DAFSA file if possible). psl_latest() gives back whatever is the newest/latest datain (psl-distfile, application provided file, psl builtin data, file that psl builtin data is derived from).

**Comment by KellerFuchs** [comment]
@rockdaboot Looks good to me, modulo the comments I left on the commit.

**Comment by rockdaboot** [comment]
Thanks for feedback. Added/amended comments and pushed.
