### ISSUE TITLE
psl --print-info prints 0 for dist DAFSA

### ISSUE THREAD

**Issue by andreasstieger** [rockdaboot/libpsl#77]
Built from 0.16.1 tarball with:

`./configure [...] --with-psl-file=/usr/share/publicsuffix/public_suffix_list.dat --with-psl-distfile=/usr/share/publicsuffix/public_suffix_list.dafsa`

`--print-info` shows zeroes for the stats in the dist data:

    psl --print-info
    dist filename: /usr/share/publicsuffix/public_suffix_list.dafsa
    suffixes: 0
    exceptions: 0
    wildcards: 0
    builtin suffixes: 6622
    builtin exceptions: 8
    builtin wildcards: 51
    builtin filename: /usr/share/publicsuffix/public_suffix_list.dat
    builtin file time: 1481474603 (Sun, 11 Dec 2016 17:43:23 CET)
    builtin SHA1 file hash: c0fa047ad5c7e4be7dacb12b439152e5ee5cba64
    builtin outdated: 0

**Comment by rockdaboot** [comment]
DAFSA does not contain that information. Should we say 'not avail' instead of 0 ? 0 is a bit misleading...

**Comment by rockdaboot** [comment]
Thanks, correction pushed.

**Comment by andreasstieger** [comment]
4e51142022e4e2a57a65aa4fd4e3a66ba6041602 thx
