### ISSUE TITLE
`--print-reg-domain` and `--print-unreg-domain` does not handle invalid domains

### ISSUE THREAD

**Issue by tgxworld** [rockdaboot/libpsl#84]
> or %NULL if @domain * does not contain a public suffix

```
$ psl --print-reg-domain asdasdas.dasdasdas.123123asdiasdiqweiouqwia
asdasdas.dasdasdas.123123asdiasdiqweiouqwia: dasdasdas.123123asdiasdiqweiouqwia
$ psl --print-unreg-domain asdasdas.dasdasdas.123123asdiasdiqweiouqwia
asdasdas.dasdasdas.123123asdiasdiqweiouqwia: 123123asdiasdiqweiouqwia
```

### Version
```
psl 0.17.0 (0x001100)
libpsl 0.17.0 (+libidn2/0.16)

Copyright (C) 2014-2016 Tim Ruehsen
License: MIT
```

**Comment by rockdaboot** [comment]
That is on purpose. libpsl applies a technical algorithm to your input string. And technically, the output is correct. It is beyond the scope of libpsl to check if a domain exists in the real world.

BTW, you should *really* update your libpsl *and* libidn2. Several security bugs have been fixed since your versions.

**Comment by tgxworld** [comment]
> And technically, the output is correct. It is beyond the scope of libpsl to check if a domain exists in the real world.

Thank you for the quick response! Am I mis-understanding something but shouldn't the function return NULL if the given domain does not contain a public suffix?

**Comment by rockdaboot** [comment]
A TLD is never a public suffix (so-called * rule). So your unknown TLD `123123asdiasdiqweiouqwia` is like being implicitly in the public suffix list.  So, technically, it is treated as being a public suffix.

```
$ psl --is-public-suffix 123123asdiasdiqweiouqwia
123123asdiasdiqweiouqwia: 1
$ psl --is-public-suffix x.123123asdiasdiqweiouqwia
x.123123asdiasdiqweiouqwia: 0
```

**Comment by tgxworld** [comment]
> A TLD is never a public suffix (so-called * rule) 

Can I check if there is a way to lookup/match TLD against the list? For example, I want to find out if `bh` is part of the public suffix list but currently `bh1` would return 1 as well.

**Comment by rockdaboot** [comment]
In fact *any* TLD is *implicitly* a PSL. But here are two sections, ICANN and PRIVATE.
The `psl` tool doesn't have options to specify this and thus always uses ANY (patches welcome).

But the library has `psl_is_public_suffix2()` which takes PSL_TYPE_PRIVATE, PSL_TYPE_ICANN or PSL_TYPE_ANY as third param.

But if you just want to find out if a TLD is an 'official' TLD, the Public Suffix List is not the appropriate database.

**Comment by rockdaboot** [comment]
You can find the official list of TLDs [here](http://data.iana.org/TLD/tlds-alpha-by-domain.txt)

**Comment by tgxworld** [comment]
@rockdaboot Thank you for the clarifications :) Appreciate it
