### ISSUE TITLE
configure --enable-builtin/--disable-builtin is now dead code

### ISSUE THREAD

**Issue by crigler** [rockdaboot/libpsl#91]
It looks like having libidn2/libicu/libidn is no longer needed to generate
the built-in PSL data; the BUILTIN_GENERATOR_* defines are no longer used
anywhere except in the psl_builtin() function, and suffixes_dafsa.c is
compiled even if --disable-builtin is used.

**Comment by rockdaboot** [comment]
Not sure what you mean. You want to say that there is a bug in the build when using --disable-builtin ? (Possibly yes).

**Comment by rockdaboot** [comment]
Fixed in master, thanks.

**Comment by crigler** [comment]
I mean I was able to get --enable-builtin --disable-runtime to work without any of the external libraries installed by removing the configure tests for libidn2, libicu, and libidn from --enable-builtin, and removing all references to BUILTIN_GENERATOR_LIBICU, BUILTIN_GENERATOR_LIBIDN2 and BUILTIN_GENERATOR_LIBIDN everywhere.

See [this patch](https://github.com/rockdaboot/libpsl/files/1781922/libpsl-builtin-no-libs-1.diff.txt).
