### ISSUE TITLE
Regression libpsl.so.6 -> libpsl.so.5.3.0

### ISSUE THREAD

**Issue by hanvinke** [rockdaboot/libpsl#93]
The latest ARCH update to libpsl  0.20.1-1 downgrades libpsl to version libpsl.so.5.3.0.
Please fix.

**Comment by rockdaboot** [comment]
0.20.1 is a fix for 0.20.0 where we accidentally increased the version to 6.
Sorry for the hassle, but this has been discussed and we decided for this measurement.
