### ISSUE TITLE
Port build system to meson

### ISSUE THREAD

**Issue by nacho** [rockdaboot/libpsl#95]
Now that libsoup depends on libpsl we will need to port it to meson so we can build it on windows with msvc.

**Comment by rockdaboot** [comment]
Ok, but why is it an issue ? Any blockers ?

**Comment by nacho** [comment]
No, just want to track the work here since I pointed it out on the bug report of libsoup.

**Comment by rockdaboot** [comment]
Now I got it, just remembered @csaavedra ;-) Was #90 about the NO_STAR_RULE.

I have no idea about Meson, but if a build script / file fit's into here, it's definitely appreciated.

**Comment by fanc999** [comment]
Hi @nacho,

Since getting all supported platforms to build with Meson is a bit beyond my reach, my current plan is to get the MSVC/NMake and autotools (please see PR #97/#98) working, and then move on to Meson.

My take at this.

With blessings, and cheers!

**Comment by rockdaboot** [comment]
After merging PR #99, is there anything that should go into a 0.20.2 release ?

**Comment by fanc999** [comment]
Hi @rockdaboot,

I think for this issue we should be all set, sans the Meson port, but the Windows builds should be covered by now.

With blessings and cheers!

**Comment by nacho** [comment]
@fanc999 thanks a lot for working on this!

**Comment by nacho** [comment]
@rockdaboot can I ask you for a new release at this point? That way I can add it to gvsbuild

**Comment by rockdaboot** [comment]
@nacho Definitely. For some reason the man page wasn't generated... will debug tomorrow. This is the last blocker, of course popping up when manually checking the prepared release tarball *grrr*.

**Comment by rockdaboot** [comment]
@nacho Release is out now. Thanks to all people involved !

BTW, is libsoup interested in a libhsts which gives easy access to the Chromium HSTS data ?
It started at https://gitlab.com/rockdaboot/libhsts. It currently works with a similar DAFSA approach as libpsl, so condenses the data from >5mb to 300k with a separate tool.

**Comment by csaavedra** [comment]
We're currently implementing a HSTS session feature in libsoup. At some point we might want to add a preload list and then libhsts would come really handy. I'll have a loot at it. Thanks for the pointer!

**Comment by xclaesse** [comment]
I was trying to build libsoup for Android, and having its dependencies as Meson subproject would help a lot. Found this bug report about adding Meson build system, is it still planned to happen? Or would patches be accepted upstream?

**Comment by nacho** [comment]
@xclaesse I did not have time to get to it.... any chance you coudl deal with it and we can fix the windows part

**Comment by rockdaboot** [comment]
@xclaesse Patches are welcome, of course :-)

**Comment by rockdaboot** [comment]
Closing due to #113

**Comment by fanc999** [comment]
Hi @nacho,

Eventually I agree.  I will try to take a look at this tomorrow to see how this works without using any hand-created pkg-config files.

It does seem at first glance that we need to search for ICU manually for Visual Studio builds if its pkg-config files cannot be found, since ICU's project files do not generate pkg-config files.

With blessings, thank you

**Comment by rockdaboot** [comment]
Please check http://userguide.icu-project.org/howtouseicu, the use of pkg-config files is recommended now.

**Comment by nacho** [comment]
@rockdaboot note that is usually true for linux systems but on widnows they usually do not ship the pkg-config files. @fanc999 afaik @xclaesse added the fallback to find_library.

**Comment by xclaesse** [comment]
As long as the headers and the dll is installed in msvc search paths it should work without pkg-config file. But I haven't tested, feedback welcome.

**Comment by xclaesse** [comment]
oh there is that ugly use of the 'printf' command that won't work unless you're using msys2 I guess? It should be possible to avoid doing that in the build system with some smarter #define I guess?

**Comment by rockdaboot** [comment]
just pushed include/meson.build without the external printf command.
